// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace Leopard.Repository
{
    public partial class LeopardDbContextFactory : IDesignTimeDbContextFactory<LeopardDbContext>
    {
        public LeopardDbContext CreateDbContext(string[] args)
        {
            return new LeopardDbContext();
        }
    }
}
// </auto-generated>
