// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    // SAMT_Agents
    public partial class SamtAgent
    {
       
        // Reverse navigation

        /// <summary>
        /// Child TelavatAgentResourceTypes where [TelavatAgentResourceTypes].[AgentID] point to this entity (FK_TelavatAgentResourceTypes_SAMT_Agents)
        /// </summary>
        public virtual ICollection<TelavatAgentResourceType> TelavatAgentResourceTypes { get; set; } // TelavatAgentResourceTypes.FK_TelavatAgentResourceTypes_SAMT_Agents

        partial void InitializePartial() {
			TelavatAgentResourceTypes = new List<TelavatAgentResourceType>();
		}
    }

}
// </auto-generated>
