// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Shift.Repository
{
    // Shift_ShiftTabletPayments
    public partial class ShiftShiftTabletPaymentConfiguration : IEntityTypeConfiguration<ShiftShiftTabletPayment>
    {
        public void Configure(EntityTypeBuilder<ShiftShiftTabletPayment> builder)
        {
            builder.ToTable("Shift_ShiftTabletPayments", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Shift_ShiftTabletPayments").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.AgentId).HasColumnName(@"AgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.DateFrom).HasColumnName(@"DateFrom").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.DateTo).HasColumnName(@"DateTo").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.YearPersian).HasColumnName(@"YearPersian").HasColumnType("int").IsRequired();
            builder.Property(x => x.MonthPersian).HasColumnName(@"MonthPersian").HasColumnType("int").IsRequired();
            builder.Property(x => x.MandatoryShiftCount).HasColumnName(@"MandatoryShiftCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.NonMandatoryShiftCount).HasColumnName(@"NonMandatoryShiftCount").HasColumnType("int").IsRequired();
            builder.Property(x => x.CalculatedPayment).HasColumnName(@"CalculatedPayment").HasColumnType("decimal(19,4)").HasPrecision(19,4).IsRequired();
            builder.Property(x => x.FinalPayment).HasColumnName(@"FinalPayment").HasColumnType("decimal(19,4)").HasPrecision(19,4).IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.ShiftShiftTabletPayments).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Shift_ShiftTabletPayments_Portals");
            builder.HasOne(a => a.SamtAgent).WithMany(b => b.ShiftShiftTabletPayments).HasForeignKey(c => c.AgentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Shift_ShiftTabletPayments_SAMT_Agents");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ShiftShiftTabletPayment> builder);
    }

}
// </auto-generated>
