// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Shift.Repository
{
    // Shift_Log
    public partial class ShiftLogConfiguration : IEntityTypeConfiguration<ShiftLog>
    {
        public void Configure(EntityTypeBuilder<ShiftLog> builder)
        {
            builder.ToTable("Shift_Log", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Shift_Log").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Message).HasColumnName(@"Message").HasColumnType("text(2147483647)").IsRequired(false).IsUnicode(false).HasMaxLength(2147483647);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ShiftLog> builder);
    }

}
// </auto-generated>
