// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Shift.Repository
{
    // TelavatAgentResourceTypes
    public partial class TelavatAgentResourceTypeConfiguration : IEntityTypeConfiguration<TelavatAgentResourceType>
    {
        public void Configure(EntityTypeBuilder<TelavatAgentResourceType> builder)
        {
            builder.ToTable("TelavatAgentResourceTypes", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatAgentResourceTypes").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.AgentId).HasColumnName(@"AgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ResourceTypeId).HasColumnName(@"ResourceTypeID").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatAgentResourceType> builder);
    }

}
// </auto-generated>
