// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Shift.Repository
{
    // UserTypeGroupRoleMenus
    public partial class UserTypeGroupRoleMenuConfiguration : IEntityTypeConfiguration<UserTypeGroupRoleMenu>
    {
        public void Configure(EntityTypeBuilder<UserTypeGroupRoleMenu> builder)
        {
            builder.ToTable("UserTypeGroupRoleMenus", "dbo");
            builder.HasKey(x => new { x.RayanMenuId, x.UserTypeGroupId, x.PermissionType }).HasName("PK_UserTypeGroupRoles").IsClustered();

            builder.Property(x => x.RayanMenuId).HasColumnName(@"RayanMenuID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserTypeGroupId).HasColumnName(@"UserTypeGroupID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PermissionType).HasColumnName(@"PermissionType").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.UserTypeGroup).WithMany(b => b.UserTypeGroupRoleMenus).HasForeignKey(c => c.UserTypeGroupId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserTypeGroupRole_UserTypeGroups");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<UserTypeGroupRoleMenu> builder);
    }

}
// </auto-generated>
