// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    public partial interface IShiftLogStore : IStoreBase<ShiftLog>
    {
    }
}
// </auto-generated>
