// <auto-generated>
// ReSharper disable All

using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    public partial class Samtv3MonitoringAttachmentStore : StoreBase<Samtv3MonitoringAttachment>, ISamtv3MonitoringAttachmentStore
    {
        private readonly ILeopardDbContext _ctx;
        private readonly ILogger _logger;
        private readonly IPrincipal _iPrincipal;

        public Samtv3MonitoringAttachmentStore(ILeopardDbContext ctx, ILogger logger, IPrincipal principal) : base(ctx, logger, principal)
        {
            _ctx = ctx;
    		_logger = logger;
            _iPrincipal = principal;
        }
    }
}
// </auto-generated>
