// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatAgentResourceTypes
    public partial class TelavatAgentResourceTypeConfiguration : IEntityTypeConfiguration<TelavatAgentResourceType>
    {
        partial void InitializePartial(EntityTypeBuilder<TelavatAgentResourceType> builder) {
			// Foreign keys
			builder.HasOne(a => a.SamtAgent).WithMany(b => b.TelavatAgentResourceTypes).HasForeignKey(c => c.AgentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatAgentResourceTypes_SAMT_Agents");
			builder.HasOne(a => a.SamtResourceType).WithMany(b => b.TelavatAgentResourceTypes).HasForeignKey(c => c.ResourceTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatAgentResourceTypes_SAMT_ResourceTypes");
		}
    }

}
// </auto-generated>
