// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Advertises
    public partial class Advertis
    {
        public int Id { get; set; } // ID (Primary key)
        public int CategoryId { get; set; } // CategoryID
        public string FileName { get; set; } // FileName (length: 255)
        public string LinkUrl { get; set; } // LinkURL (length: 255)
        public int Ordering { get; set; } // Ordering
        public bool Enabled { get; set; } // Enabled
        public string Description { get; set; } // Description
        public int WidthFlash { get; set; } // WidthFlash
        public int HeightFlash { get; set; } // HeightFlash

        // Foreign keys

        /// <summary>
        /// Parent AdvertiseCategory pointed by [Advertises].([CategoryId]) (FK_Advertises_AdvertiseCategories)
        /// </summary>
        public virtual AdvertiseCategory AdvertiseCategory { get; set; } // FK_Advertises_AdvertiseCategories

        public Advertis()
        {
            Enabled = false;
            WidthFlash = 0;
            HeightFlash = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
