// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ApiResourceProperties
    public partial class ApiResourceProperty
    {
        public int Id { get; set; } // Id (Primary key)
        public int ApiResourceId { get; set; } // ApiResourceId
        public string Key { get; set; } // Key (length: 250)
        public string Value { get; set; } // Value (length: 2000)

        // Foreign keys

        /// <summary>
        /// Parent ApiResource pointed by [ApiResourceProperties].([ApiResourceId]) (FK_ApiResourceProperties_ApiResources_ApiResourceId)
        /// </summary>
        public virtual ApiResource ApiResource { get; set; } // FK_ApiResourceProperties_ApiResources_ApiResourceId

        public ApiResourceProperty()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
