// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ApiResourceScopes
    public partial class ApiResourceScope
    {
        public int Id { get; set; } // Id (Primary key)
        public string Scope { get; set; } // Scope (length: 200)
        public int ApiResourceId { get; set; } // ApiResourceId

        // Foreign keys

        /// <summary>
        /// Parent ApiResource pointed by [ApiResourceScopes].([ApiResourceId]) (FK_ApiResourceScopes_ApiResources_ApiResourceId)
        /// </summary>
        public virtual ApiResource ApiResource { get; set; } // FK_ApiResourceScopes_ApiResources_ApiResourceId

        public ApiResourceScope()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
