// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ApiScopes
    public partial class ApiScope
    {
        public int Id { get; set; } // Id (Primary key)
        public bool Enabled { get; set; } // Enabled
        public string Name { get; set; } // Name (length: 200)
        public string DisplayName { get; set; } // DisplayName (length: 200)
        public string Description { get; set; } // Description (length: 1000)
        public bool Required { get; set; } // Required
        public bool Emphasize { get; set; } // Emphasize
        public bool ShowInDiscoveryDocument { get; set; } // ShowInDiscoveryDocument

        // Reverse navigation

        /// <summary>
        /// Child ApiScopeClaims where [ApiScopeClaims].[ScopeId] point to this entity (FK_ApiScopeClaims_ApiScopes_ScopeId)
        /// </summary>
        public virtual ICollection<ApiScopeClaim> ApiScopeClaims { get; set; } // ApiScopeClaims.FK_ApiScopeClaims_ApiScopes_ScopeId

        /// <summary>
        /// Child ApiScopeProperties where [ApiScopeProperties].[ScopeId] point to this entity (FK_ApiScopeProperties_ApiScopes_ScopeId)
        /// </summary>
        public virtual ICollection<ApiScopeProperty> ApiScopeProperties { get; set; } // ApiScopeProperties.FK_ApiScopeProperties_ApiScopes_ScopeId

        public ApiScope()
        {
            ApiScopeClaims = new List<ApiScopeClaim>();
            ApiScopeProperties = new List<ApiScopeProperty>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
