// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // BaseInfoCategories
    public partial class BaseInfoCategory
    {
        public int Id { get; set; } // ID
        public string Title { get; set; } // Title (length: 50)
        public int BaseCategoryId { get; set; } // BaseCategoryID (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child BaseInfoes where [BaseInfos].[BaseInfoCategoryID] point to this entity (FK_BaseInfos_BaseInfoCategories)
        /// </summary>
        public virtual ICollection<BaseInfo> BaseInfoes { get; set; } // BaseInfos.FK_BaseInfos_BaseInfoCategories

        /// <summary>
        /// Child UserProfiles where [UserProfiles].[BaseInfoCategoryID] point to this entity (FK_UserProfiles_BaseInfoCategories)
        /// </summary>
        public virtual ICollection<UserProfile> UserProfiles { get; set; } // UserProfiles.FK_UserProfiles_BaseInfoCategories

        public BaseInfoCategory()
        {
            BaseInfoes = new List<BaseInfo>();
            UserProfiles = new List<UserProfile>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
