// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Cities
    public partial class City
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 100)
        public int StateId { get; set; } // StateID

        public City()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
