// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ClientIdPRestrictions
    public partial class ClientIdPRestriction
    {
        public int Id { get; set; } // Id (Primary key)
        public string Provider { get; set; } // Provider (length: 200)
        public int ClientId { get; set; } // ClientId

        // Foreign keys

        /// <summary>
        /// Parent Client pointed by [ClientIdPRestrictions].([ClientId]) (FK_ClientIdPRestrictions_Clients_ClientId)
        /// </summary>
        public virtual Client Client { get; set; } // FK_ClientIdPRestrictions_Clients_ClientId

        public ClientIdPRestriction()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
