// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ClientPostLogoutRedirectUris
    public partial class ClientPostLogoutRedirectUri
    {
        public int Id { get; set; } // Id (Primary key)
        public string PostLogoutRedirectUri { get; set; } // PostLogoutRedirectUri (length: 2000)
        public int ClientId { get; set; } // ClientId

        // Foreign keys

        /// <summary>
        /// Parent Client pointed by [ClientPostLogoutRedirectUris].([ClientId]) (FK_ClientPostLogoutRedirectUris_Clients_ClientId)
        /// </summary>
        public virtual Client Client { get; set; } // FK_ClientPostLogoutRedirectUris_Clients_ClientId

        public ClientPostLogoutRedirectUri()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
