// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorItemDispatch
    public partial class ConductorItemDispatch
    {
        public int Id { get; set; } // ID (Primary key)

        /// <summary>
        /// بازبین 1 - تدوین 2
        /// </summary>
        public int? UnitType { get; set; } // UnitType
        public int? RequestId { get; set; } // RequestID
        public int FromUserId { get; set; } // FromUserID
        public int? ToUserId { get; set; } // ToUserID
        public string Description { get; set; } // Description
        public bool? IsViewed { get; set; } // IsViewed
        public string ArchiveDescription { get; set; } // ArchiveDescription (length: 1000)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public string TotalTime { get; set; } // TotalTime (length: 10)
        public int BazbinStatus { get; set; } // BazbinStatus
        public bool IsArchived { get; set; } // IsArchived
        public int? ProgramOrientation { get; set; } // ProgramOrientation
        public string ProgramSubject { get; set; } // ProgramSubject (length: 100)
        public string ProgramOccasion { get; set; } // ProgramOccasion (length: 100)
        public string SoundBand { get; set; } // SoundBand (length: 50)
        public string Director { get; set; } // Director (length: 50)
        public string Moderator { get; set; } // Moderator (length: 50)
        public string CommercialTime { get; set; } // CommercialTime (length: 50)
        public string SubtitleTime { get; set; } // SubtitleTime (length: 50)
        public string Actors { get; set; } // Actors
        public string Experts { get; set; } // Experts
        public string ProgramSummary { get; set; } // ProgramSummary
        public int? ChannelId { get; set; } // ChannelId
        public int? ProgramId { get; set; } // ProgramId
        public int? ClacketNo { get; set; } // ClacketNo
        public int StepId { get; set; } // StepId
        public string DescriptionManager { get; set; } // DescriptionManager
        public int PassedStepId { get; set; } // PassedStepId
        public int StatusId { get; set; } // StatusId
        public int? TadvinStatus { get; set; } // TadvinStatus
        public int FirstBazbinStatus { get; set; } // FirstBazbinStatus
        public string ReportDesc { get; set; } // ReportDesc
        public int? TadvinDispatchId { get; set; } // TadvinDispatchID
        public DateTime? FirstBazbinDateTime { get; set; } // FirstBazbinDateTime
        public DateTime? BazbinDateTime { get; set; } // BazbinDateTime
        public DateTime? SendToBazbinDateTime { get; set; } // SendToBazbinDateTime
        public string DescManagerForBazbin { get; set; } // DescManagerForBazbin (length: 1000)
        public string BazbinDescription { get; set; } // BazbinDescription (length: 500)

        // Reverse navigation

        /// <summary>
        /// Child ConductorDispatchDetails where [ConductorDispatchDetails].[TadvinDispatchID] point to this entity (FK_ConductorDispatchDetails_ConductorItemDispatch1)
        /// </summary>
        public virtual ICollection<ConductorDispatchDetail> ConductorDispatchDetails { get; set; } // ConductorDispatchDetails.FK_ConductorDispatchDetails_ConductorItemDispatch1

        /// <summary>
        /// Child ConductorItemDispatches where [ConductorItemDispatch].[TadvinDispatchID] point to this entity (FK_ConductorItemDispatch_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<ConductorItemDispatch> ConductorItemDispatches { get; set; } // ConductorItemDispatch.FK_ConductorItemDispatch_ConductorItemDispatch

        /// <summary>
        /// Child ConductorItemDispatchAgents where [ConductorItemDispatchAgents].[DispatchID] point to this entity (FK_ConductorItemDispatchAgents_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<ConductorItemDispatchAgent> ConductorItemDispatchAgents { get; set; } // ConductorItemDispatchAgents.FK_ConductorItemDispatchAgents_ConductorItemDispatch

        /// <summary>
        /// Child ConductorItemDispatchEvents where [ConductorItemDispatchEvents].[DispatchID] point to this entity (FK_ConductorItemDispatchEvents_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<ConductorItemDispatchEvent> ConductorItemDispatchEvents { get; set; } // ConductorItemDispatchEvents.FK_ConductorItemDispatchEvents_ConductorItemDispatch

        /// <summary>
        /// Child ConductorItemDispatchLogs where [ConductorItemDispatchLogs].[DispatchID] point to this entity (FK_ConductorItemDispatchLogs_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<ConductorItemDispatchLog> ConductorItemDispatchLogs { get; set; } // ConductorItemDispatchLogs.FK_ConductorItemDispatchLogs_ConductorItemDispatch

        /// <summary>
        /// Child ConductorItemDispatchSubjects where [ConductorItemDispatchSubjects].[DispatchID] point to this entity (FK_ConductorItemDispatchSubjects_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<ConductorItemDispatchSubject> ConductorItemDispatchSubjects { get; set; } // ConductorItemDispatchSubjects.FK_ConductorItemDispatchSubjects_ConductorItemDispatch

        /// <summary>
        /// Child DispatchTypeValues where [DispatchTypeValue].[DispatchId] point to this entity (FK_DispatchTypeValue_ConductorItemDispatch)
        /// </summary>
        public virtual ICollection<DispatchTypeValue> DispatchTypeValues { get; set; } // DispatchTypeValue.FK_DispatchTypeValue_ConductorItemDispatch

        // Foreign keys

        /// <summary>
        /// Parent ConductorItemDispatch pointed by [ConductorItemDispatch].([TadvinDispatchId]) (FK_ConductorItemDispatch_ConductorItemDispatch)
        /// </summary>
        public virtual ConductorItemDispatch TadvinDispatch { get; set; } // FK_ConductorItemDispatch_ConductorItemDispatch

        /// <summary>
        /// Parent ConductorTablePakhsh pointed by [ConductorItemDispatch].([RequestId]) (FK_ConductorItemDispatch_ConductorTablePakhsh)
        /// </summary>
        public virtual ConductorTablePakhsh ConductorTablePakhsh { get; set; } // FK_ConductorItemDispatch_ConductorTablePakhsh

        /// <summary>
        /// Parent ProcessStatu pointed by [ConductorItemDispatch].([StatusId]) (FK_ConductorItemDispatch_ProcessStatus)
        /// </summary>
        public virtual ProcessStatu ProcessStatu { get; set; } // FK_ConductorItemDispatch_ProcessStatus

        /// <summary>
        /// Parent ProcessStep pointed by [ConductorItemDispatch].([PassedStepId]) (FK_ConductorItemDispatch_ProcessSteps1)
        /// </summary>
        public virtual ProcessStep PassedStep { get; set; } // FK_ConductorItemDispatch_ProcessSteps1

        /// <summary>
        /// Parent ProcessStep pointed by [ConductorItemDispatch].([StepId]) (FK_ConductorItemDispatch_ProcessSteps)
        /// </summary>
        public virtual ProcessStep Step { get; set; } // FK_ConductorItemDispatch_ProcessSteps

        public ConductorItemDispatch()
        {
            IsViewed = false;
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            BazbinStatus = 0;
            IsArchived = false;
            StepId = 1;
            FirstBazbinStatus = 0;
            ConductorDispatchDetails = new List<ConductorDispatchDetail>();
            ConductorItemDispatches = new List<ConductorItemDispatch>();
            ConductorItemDispatchAgents = new List<ConductorItemDispatchAgent>();
            ConductorItemDispatchEvents = new List<ConductorItemDispatchEvent>();
            ConductorItemDispatchLogs = new List<ConductorItemDispatchLog>();
            ConductorItemDispatchSubjects = new List<ConductorItemDispatchSubject>();
            DispatchTypeValues = new List<DispatchTypeValue>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
