// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorItemDispatchSubjects
    public partial class ConductorItemDispatchSubject
    {
        public int Id { get; set; } // ID (Primary key)
        public int DispatchId { get; set; } // DispatchID
        public int SubjectId { get; set; } // SubjectID
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Foreign keys

        /// <summary>
        /// Parent ConductorItemDispatch pointed by [ConductorItemDispatchSubjects].([DispatchId]) (FK_ConductorItemDispatchSubjects_ConductorItemDispatch)
        /// </summary>
        public virtual ConductorItemDispatch ConductorItemDispatch { get; set; } // FK_ConductorItemDispatchSubjects_ConductorItemDispatch

        /// <summary>
        /// Parent SamtSubject pointed by [ConductorItemDispatchSubjects].([SubjectId]) (FK_ConductorItemDispatchSubjects_SAMT_Subjects)
        /// </summary>
        public virtual SamtSubject SamtSubject { get; set; } // FK_ConductorItemDispatchSubjects_SAMT_Subjects

        public ConductorItemDispatchSubject()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
