// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorSendHistory
    public partial class ConductorSendHistory
    {
        public int Id { get; set; } // ID (Primary key)
        public int ChannelId { get; set; } // ChannelId
        public string BroadcastDate { get; set; } // BroadcastDate (length: 10)
        public int ConductorId { get; set; } // ConductorId
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public DateTime? UsedAtDateTime { get; set; } // UsedAtDateTime

        public ConductorSendHistory()
        {
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
