// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorChannelProgramInTags
    public partial class ConductorChannelProgramInTag
    {
        public int Id { get; set; } // ID (Primary key)
        public int ConductorChannelProgramId { get; set; } // ConductorChannelProgramID
        public int TagId { get; set; } // TagID

        // Foreign keys

        /// <summary>
        /// Parent ConductorChannelProgram pointed by [ConductorChannelProgramInTags].([ConductorChannelProgramId]) (FK_ConductorChannelProgramInTags_ConductorChannelPrograms)
        /// </summary>
        public virtual ConductorChannelProgram ConductorChannelProgram { get; set; } // FK_ConductorChannelProgramInTags_ConductorChannelPrograms

        /// <summary>
        /// Parent ConductorChannelProgramTag pointed by [ConductorChannelProgramInTags].([TagId]) (FK_ConductorChannelProgramInTags_ConductorChannelProgramTags)
        /// </summary>
        public virtual ConductorChannelProgramTag ConductorChannelProgramTag { get; set; } // FK_ConductorChannelProgramInTags_ConductorChannelProgramTags

        public ConductorChannelProgramInTag()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
