// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorSubTitles
    public partial class ConductorSubTitle
    {
        public int Id { get; set; } // ID (Primary key)
        public int? ConductorId { get; set; } // ConductorID
        public string StartTime { get; set; } // StartTime (length: 150)
        public string Description { get; set; } // Description (length: 1073741823)
        public int CreatedBy { get; set; } // CreatedBy
        public DateTime CreateDatetime { get; set; } // CreateDatetime
        public int? DeletedBy { get; set; } // DeletedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? LastModificationDatetime { get; set; } // LastModificationDatetime
        public int ItemType { get; set; } // ItemType
        public int? ProgramId { get; set; } // ProgramId
        public int? ClacketNo { get; set; } // ClacketNo

        public ConductorSubTitle()
        {
            CreateDatetime = DateTime.Now;
            ItemType = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
