// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorOfogh
    public partial class ConductorOfogh
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public string Time { get; set; } // Time (length: 1000)
        public int Status { get; set; } // Status
        public int Ordering { get; set; } // Ordering
        public DateTime StartDate { get; set; } // StartDate
        public DateTime EndDate { get; set; } // EndDate
        public int Channelid { get; set; } // channelid

        public ConductorOfogh()
        {
            Ordering = 1;
            StartDate = DateTime.Now;
            EndDate = DateTime.Now;
            Channelid = 6;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
