// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ConductorProgramTypes
    public partial class ConductorProgramType
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public string NumberColor { get; set; } // NumberColor (length: 100)

        public ConductorProgramType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
