// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ContentsTabbed
    public partial class ContentsTabbed
    {
        public int Id { get; set; } // ID (Primary key)
        public int GroupId { get; set; } // GroupID
        public string Title { get; set; } // Title (length: 4000)
        public int ContentType { get; set; } // contentType
        public int ContentId { get; set; } // ContentID
        public string ContentControl { get; set; } // ContentControl (length: 4000)
        public int PortalId { get; set; } // PortalID
        public bool Enabled { get; set; } // Enabled
        public int Ordering { get; set; } // Ordering
        public int ContentLeftId { get; set; } // ContentLeftID
        public string ContentleftControl { get; set; } // ContentleftControl (length: 4000)
        public string Icon { get; set; } // icon (length: 250)
        public string Link { get; set; } // Link (length: 250)
        public int ColumnsCount { get; set; } // columnsCount

        // Foreign keys

        /// <summary>
        /// Parent ContentTabGroup pointed by [ContentsTabbed].([GroupId]) (FK_ContentsTabbed_ContentsTabbed)
        /// </summary>
        public virtual ContentTabGroup ContentTabGroup { get; set; } // FK_ContentsTabbed_ContentsTabbed

        public ContentsTabbed()
        {
            GroupId = 1;
            ContentType = 0;
            ContentId = 0;
            ContentControl = "news";
            PortalId = 0;
            Enabled = true;
            Ordering = 0;
            ContentLeftId = 0;
            ContentleftControl = "";
            Icon = "";
            Link = "";
            ColumnsCount = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
