// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // DateFormats
    public partial class DateFormat
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public string Format { get; set; } // Format (length: 500)

        public DateFormat()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
