// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // FIDS_TelavatRequestPayments
    public partial class FidsTelavatRequestPayment
    {
        public int Id { get; set; } // ID (Primary key)
        public int RequestId { get; set; } // RequestID (Primary key)
        public double Amount { get; set; } // Amount (Primary key)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool IsCreditor { get; set; } // IsCreditor (Primary key)
        public DateTime? DatePayment { get; set; } // DatePayment
        public int? Type { get; set; } // Type
        public int BaseYear { get; set; } // BaseYear (Primary key)

        public FidsTelavatRequestPayment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
