// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // HijriCalendarAdjustments
    public partial class HijriCalendarAdjustment
    {
        public int Id { get; set; } // ID (Primary key)
        public int DaysInMonth { get; set; } // DaysInMonth
        public int MonthSequnce { get; set; } // MonthSequnce
        public int MonthAdjustment { get; set; } // MonthAdjustment

        public HijriCalendarAdjustment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
