// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // IdentityResourceClaims
    public partial class IdentityResourceClaim
    {
        public int Id { get; set; } // Id (Primary key)
        public int IdentityResourceId { get; set; } // IdentityResourceId
        public string Type { get; set; } // Type (length: 200)

        // Foreign keys

        /// <summary>
        /// Parent IdentityResource pointed by [IdentityResourceClaims].([IdentityResourceId]) (FK_IdentityResourceClaims_IdentityResources_IdentityResourceId)
        /// </summary>
        public virtual IdentityResource IdentityResource { get; set; } // FK_IdentityResourceClaims_IdentityResources_IdentityResourceId

        public IdentityResourceClaim()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
