// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ImageGalleries
    public partial class ImageGallery
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public bool Enabled { get; set; } // Enabled
        public int GalleryType { get; set; } // GalleryType
        public int Ordering { get; set; } // Ordering
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child ImageAlbums where [ImageAlbums].[GalleryID] point to this entity (FK_ImageAlbums_ImageGalleries)
        /// </summary>
        public virtual ICollection<ImageAlbum> ImageAlbums { get; set; } // ImageAlbums.FK_ImageAlbums_ImageGalleries

        public ImageGallery()
        {
            GalleryType = 0;
            Ordering = 0;
            ImageAlbums = new List<ImageAlbum>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
