// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ImagePhotos
    public partial class ImagePhoto
    {
        public int Id { get; set; } // ID (Primary key)
        public int AlbumId { get; set; } // AlbumID
        public string Title { get; set; } // Title (length: 50)
        public string Description { get; set; } // Description
        public bool Enabled { get; set; } // Enabled
        public int Ordering { get; set; } // Ordering
        public byte[] PhotoByte { get; set; } // PhotoByte
        public string PhotoType { get; set; } // PhotoType (length: 5)
        public bool Selected { get; set; } // Selected
        public bool SelectedGallery { get; set; } // SelectedGallery
        public bool SaveInDb { get; set; } // SaveInDB
        public string FileName { get; set; } // FileName (length: 1000)
        public string Thumbnail { get; set; } // Thumbnail (length: 1000)
        public string Thumbnail2 { get; set; } // Thumbnail2 (length: 1000)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Foreign keys

        /// <summary>
        /// Parent ImageAlbum pointed by [ImagePhotos].([AlbumId]) (FK_ImagePhotos_ImageAlbums)
        /// </summary>
        public virtual ImageAlbum ImageAlbum { get; set; } // FK_ImagePhotos_ImageAlbums

        public ImagePhoto()
        {
            SelectedGallery = false;
            SaveInDb = true;
            FileName = "";
            Thumbnail = "";
            Thumbnail2 = "";
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
