// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // InsideBaseInfo
    public partial class InsideBaseInfo
    {
        public int Id { get; set; } // ID (Primary key)
        public int Type { get; set; } // Type
        public int? ParentId { get; set; } // ParentID
        public string Title { get; set; } // Title (length: 1000)
        public bool IsDeleted { get; set; } // IsDeleted
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child ConductorDispatchDetails where [ConductorDispatchDetails].[ProblemID] point to this entity (FK_ConductorDispatchDetails_InsideBaseInfo)
        /// </summary>
        public virtual ICollection<ConductorDispatchDetail> ConductorDispatchDetails { get; set; } // ConductorDispatchDetails.FK_ConductorDispatchDetails_InsideBaseInfo

        /// <summary>
        /// Child InsideBaseInfoes where [InsideBaseInfo].[ParentID] point to this entity (FK_InsideBaseInfo_InsideBaseInfo)
        /// </summary>
        public virtual ICollection<InsideBaseInfo> InsideBaseInfoes { get; set; } // InsideBaseInfo.FK_InsideBaseInfo_InsideBaseInfo

        // Foreign keys

        /// <summary>
        /// Parent InsideBaseInfo pointed by [InsideBaseInfo].([ParentId]) (FK_InsideBaseInfo_InsideBaseInfo)
        /// </summary>
        public virtual InsideBaseInfo Parent { get; set; } // FK_InsideBaseInfo_InsideBaseInfo

        public InsideBaseInfo()
        {
            Type = 1;
            IsDeleted = false;
            ConductorDispatchDetails = new List<ConductorDispatchDetail>();
            InsideBaseInfoes = new List<InsideBaseInfo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
