// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // InternalBaravordLogs
    public partial class InternalBaravordLog
    {
        public int Id { get; set; } // ID (Primary key)
        public int? InternalResourceId { get; set; } // InternalResourceID
        public int? LogId { get; set; } // LogID
        public int? MainQualityId { get; set; } // MainQualityID
        public bool? Accept { get; set; } // Accept
        public string Description { get; set; } // Description
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool? IsDeleted { get; set; } // IsDeleted

        public InternalBaravordLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
