// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Links
    public partial class Link
    {
        public int Id { get; set; } // ID (Primary key)
        public int CategoryId { get; set; } // CategoryID
        public string Title { get; set; } // Title (length: 100)
        public string Description { get; set; } // Description
        public string Uri { get; set; } // URI (length: 500)
        public string FileName { get; set; } // FileName (length: 100)
        public int? ImageShowType { get; set; } // ImageShowType
        public bool Enabled { get; set; } // Enabled
        public DateTime CreateDateTime { get; set; } // CreateDateTime
        public int Ordering { get; set; } // Ordering
        public string Class { get; set; } // Class (length: 100)
        public bool? IsSelected { get; set; } // IsSelected

        // Foreign keys

        /// <summary>
        /// Parent LinkCategory pointed by [Links].([CategoryId]) (FK_Link_LinkCategory)
        /// </summary>
        public virtual LinkCategory LinkCategory { get; set; } // FK_Link_LinkCategory

        public Link()
        {
            Enabled = true;
            CreateDateTime = DateTime.Now;
            Ordering = 0;
            Class = "";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
