// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ME_Media
    public partial class MeMedium
    {
        public long Id { get; set; } // Id (Primary key)
        public Guid? FileInfoId { get; set; } // FileInfoId
        public long? MetaId { get; set; } // MetaId
        public long? MetaMediaFileId { get; set; } // MetaMediaFileId
        public string StreamerUrl { get; set; } // StreamerUrl
        public DateTime? RDate { get; set; } // RDate
        public int? Rownum { get; set; } // rownum
        public DateTime CreateDateTime { get; set; } // CreateDateTime (Primary key)
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        public MeMedium()
        {
            CreateDateTime = DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
