// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Menus
    public partial class Menu
    {
        public int Id { get; set; } // ID (Primary key)
        public int? MainMenuId { get; set; } // MainMenuID
        public int ParentId { get; set; } // ParentID
        public string Title { get; set; } // Title (length: 255)
        public string Link { get; set; } // Link (length: 400)
        public string MenuImage { get; set; } // MenuImage (length: 255)
        public int Ordering { get; set; } // Ordering

        /// <summary>
        /// Y=yes; N=no
        /// </summary>
        public bool Enabled { get; set; } // Enabled
        public bool LoadAsModule { get; set; } // LoadAsModule
        public string ClassName { get; set; } // ClassName (length: 1000)

        public Menu()
        {
            MainMenuId = 0;
            ParentId = 0;
            Ordering = 0;
            Enabled = false;
            LoadAsModule = false;
            ClassName = "";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
