// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // MojriReprimands
    public partial class MojriReprimand
    {
        public int Id { get; set; } // ID (Primary key)
        public int? AgentId { get; set; } // AgentID
        public string Title { get; set; } // Title (length: 500)
        public string Description { get; set; } // Description
        public string DatePersian { get; set; } // DatePersian (length: 10)
        public int? ReprimandTypeId { get; set; } // ReprimandTypeID
        public string ReprimandType { get; set; } // ReprimandType (length: 5)

        public MojriReprimand()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
