// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // NewsComments
    public partial class NewsComment
    {
        public int Id { get; set; } // ID (Primary key)
        public int? PortalId { get; set; } // PortalID
        public int? NewsId { get; set; } // NewsID
        public string Name { get; set; } // Name (length: 100)
        public string CommentText { get; set; } // commentText
        public string EmailAddress { get; set; } // EmailAddress (length: 200)
        public bool? Enabled { get; set; } // Enabled
        public string UserIp { get; set; } // UserIP (length: 15)
        public string CommentDate { get; set; } // CommentDate (length: 10)
        public string CommentTime { get; set; } // CommentTime (length: 5)
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent News pointed by [NewsComments].([NewsId]) (FK_NewsComments_News)
        /// </summary>
        public virtual News News { get; set; } // FK_NewsComments_News

        public NewsComment()
        {
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
