// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // NewsAccessUsers
    public partial class NewsAccessUser
    {
        public int Id { get; set; } // ID (Primary key)
        public int UserId { get; set; } // UserID
        public bool SetRegistered { get; set; } // SetRegistered
        public bool SetSendToActuary { get; set; } // SetSendToActuary
        public bool SetSendToEditor { get; set; } // SetSendToEditor
        public bool SetPublished { get; set; } // SetPublished
        public bool SetInVisible { get; set; } // SetInVisible
        public bool UseEditor { get; set; } // UseEditor
        public bool UseRating { get; set; } // UseRating

        public NewsAccessUser()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
