// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // NewsPriority
    public partial class NewsPriority
    {
        public int Id { get; set; } // ID (Primary key)
        public int NewsId { get; set; } // NewsID
        public int Ordering { get; set; } // Ordering
        public int PriorityId { get; set; } // PriorityID

        // Foreign keys

        /// <summary>
        /// Parent News pointed by [NewsPriority].([NewsId]) (FK_NewsPriority_News)
        /// </summary>
        public virtual News News { get; set; } // FK_NewsPriority_News

        public NewsPriority()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
