// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Pakhsh_PersonTitles
    public partial class PakhshPersonTitle
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int? CreatedBy { get; set; } // CreatedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child PakhshTabletShifts where [Pakhsh_TabletShifts].[PersonTitleID] point to this entity (FK_Pakhsh_TabletShifts_Pakhsh_PersonTitles)
        /// </summary>
        public virtual ICollection<PakhshTabletShift> PakhshTabletShifts { get; set; } // Pakhsh_TabletShifts.FK_Pakhsh_TabletShifts_Pakhsh_PersonTitles

        public PakhshPersonTitle()
        {
            PakhshTabletShifts = new List<PakhshTabletShift>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
