// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Pakhsh_Persons
    public partial class PakhshPerson
    {
        public int Id { get; set; } // ID (Primary key)
        public int AgentId { get; set; } // AgentID
        public int TitleId { get; set; } // TitleID
        public int? CreatedBy { get; set; } // CreatedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child PakhshTabletShiftLogs where [Pakhsh_TabletShiftLogs].[NextAgentID] point to this entity (FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons1)
        /// </summary>
        public virtual ICollection<PakhshTabletShiftLog> PakhshTabletShiftLogs_NextAgentId { get; set; } // Pakhsh_TabletShiftLogs.FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons1

        /// <summary>
        /// Child PakhshTabletShiftLogs where [Pakhsh_TabletShiftLogs].[PreAgentID] point to this entity (FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons)
        /// </summary>
        public virtual ICollection<PakhshTabletShiftLog> PakhshTabletShiftLogs_PreAgentId { get; set; } // Pakhsh_TabletShiftLogs.FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons

        // Foreign keys

        /// <summary>
        /// Parent SamtAgent pointed by [Pakhsh_Persons].([AgentId]) (FK_Pakhsh_Persons_SAMT_Agents)
        /// </summary>
        public virtual SamtAgent SamtAgent { get; set; } // FK_Pakhsh_Persons_SAMT_Agents

        public PakhshPerson()
        {
            PakhshTabletShiftLogs_NextAgentId = new List<PakhshTabletShiftLog>();
            PakhshTabletShiftLogs_PreAgentId = new List<PakhshTabletShiftLog>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
