// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // PortalAddresses
    public partial class PortalAddress
    {
        public int Id { get; set; } // ID (Primary key)
        public int PortalId { get; set; } // PortalID
        public string DomainAddress { get; set; } // DomainAddress (length: 60)
        public string Desciption { get; set; } // Desciption (length: 500)

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [PortalAddresses].([PortalId]) (FK_PortalAddresses_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_PortalAddresses_Portals

        public PortalAddress()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
