// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Portals
    public partial class Portal
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 200)
        public string Domain { get; set; } // Domain (length: 200)
        public int? ParentId { get; set; } // ParentID
        public string Description { get; set; } // Description (length: 1000)
        public string Alias { get; set; } // Alias (length: 20)
        public string Direction { get; set; } // Direction (length: 3)
        public string Language { get; set; } // Language (length: 6)
        public string Favicon { get; set; } // Favicon (length: 100)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool ShowHerOwnLogo { get; set; } // ShowHerOwnLogo
        public bool NoDashboard { get; set; } // NoDashboard
        public string TitleAlias { get; set; } // TitleAlias (length: 150)
        public string MetaDescription { get; set; } // MetaDescription (length: 250)
        public string MetaKeyWord { get; set; } // MetaKeyWord (length: 250)
        public string FolderAlias { get; set; } // FolderAlias (length: 250)
        public string ValidLoginIps { get; set; } // ValidLoginIps (length: 4000)
        public int Qouta { get; set; } // Qouta
        public int Ordering { get; set; } // Ordering
        public int? MoeinId { get; set; } // MoeinId
        public bool IsSelected { get; set; } // IsSelected
        public int? ChannelLatinId { get; set; } // ChannelLatinID
        public int? EpgKey { get; set; } // EPGKey
        public int? SamtId { get; set; } // SamtId
        public int? ChehrehId { get; set; } // ChehrehId
        public bool Enable { get; set; } // Enable
        public string IconName { get; set; } // IconName (length: 50)
        public int? PortalId { get; set; } // PortalID
        public string UidLevel { get; set; } // UIDLevel (length: 2)

        // Reverse navigation

        /// <summary>
        /// Child ChannelGroups where [ChannelGroups].[PortalID] point to this entity (FK_ChannelGroup_Portals)
        /// </summary>
        public virtual ICollection<ChannelGroup> ChannelGroups { get; set; } // ChannelGroups.FK_ChannelGroup_Portals

        /// <summary>
        /// Child ConductorBroadcastCertificates where [ConductorBroadcastCertificates].[ChannelID] point to this entity (FK_ConductorBroadcastCertificates_Portals)
        /// </summary>
        public virtual ICollection<ConductorBroadcastCertificate> ConductorBroadcastCertificates { get; set; } // ConductorBroadcastCertificates.FK_ConductorBroadcastCertificates_Portals

        /// <summary>
        /// Child ConductorChannelProgramTags where [ConductorChannelProgramTags].[PortalID] point to this entity (FK_ConductorChannelProgramTags_Portals)
        /// </summary>
        public virtual ICollection<ConductorChannelProgramTag> ConductorChannelProgramTags { get; set; } // ConductorChannelProgramTags.FK_ConductorChannelProgramTags_Portals

        /// <summary>
        /// Child OldTelavatGrades2 where [OLD_TelavatGrades2].[PortalID] point to this entity (FK_TelavatGrades_Portals)
        /// </summary>
        public virtual ICollection<OldTelavatGrades2> OldTelavatGrades2 { get; set; } // OLD_TelavatGrades2.FK_TelavatGrades_Portals

        /// <summary>
        /// Child PakhshChannelLocations where [Pakhsh_ChannelLocations].[ChannelID] point to this entity (FK_Pakhsh_ChanelLocations_Portals)
        /// </summary>
        public virtual ICollection<PakhshChannelLocation> PakhshChannelLocations { get; set; } // Pakhsh_ChannelLocations.FK_Pakhsh_ChanelLocations_Portals

        /// <summary>
        /// Child PakhshChannelSettings where [Pakhsh_ChannelSettings].[ChannelID] point to this entity (FK_Pakhsh_ChanelSettings_Portals)
        /// </summary>
        public virtual ICollection<PakhshChannelSetting> PakhshChannelSettings { get; set; } // Pakhsh_ChannelSettings.FK_Pakhsh_ChanelSettings_Portals

        /// <summary>
        /// Child PakhshManageShifts where [Pakhsh_ManageShifts].[ChannelID] point to this entity (FK_Pakhsh_ManageShifts_Portals)
        /// </summary>
        public virtual ICollection<PakhshManageShift> PakhshManageShifts { get; set; } // Pakhsh_ManageShifts.FK_Pakhsh_ManageShifts_Portals

        /// <summary>
        /// Child PakhshShiftSettings where [Pakhsh_ShiftSettings].[ChannelID] point to this entity (FK_Pakhsh_ShiftWorks_Portals)
        /// </summary>
        public virtual ICollection<PakhshShiftSetting> PakhshShiftSettings { get; set; } // Pakhsh_ShiftSettings.FK_Pakhsh_ShiftWorks_Portals

        /// <summary>
        /// Child PortalAddresses where [PortalAddresses].[PortalID] point to this entity (FK_PortalAddresses_Portals)
        /// </summary>
        public virtual ICollection<PortalAddress> PortalAddresses { get; set; } // PortalAddresses.FK_PortalAddresses_Portals

        /// <summary>
        /// Child RayanCounterOnlineUsers where [RayanCounterOnlineUsers].[PortalID] point to this entity (FK_RayanCounterOnlineUsers_Portals)
        /// </summary>
        public virtual ICollection<RayanCounterOnlineUser> RayanCounterOnlineUsers { get; set; } // RayanCounterOnlineUsers.FK_RayanCounterOnlineUsers_Portals

        /// <summary>
        /// Child SamtGroups where [SAMT_Groups].[PortalID] point to this entity (FK_TelavatGroups_Portals)
        /// </summary>
        public virtual ICollection<SamtGroup> SamtGroups { get; set; } // SAMT_Groups.FK_TelavatGroups_Portals

        /// <summary>
        /// Child SamtMonthlyBudgets where [SAMT_MonthlyBudgets].[PortalID] point to this entity (FK_SAMT_MonthlyBudgets_Portals)
        /// </summary>
        public virtual ICollection<SamtMonthlyBudget> SamtMonthlyBudgets { get; set; } // SAMT_MonthlyBudgets.FK_SAMT_MonthlyBudgets_Portals

        /// <summary>
        /// Child SamtRequests where [SAMT_Requests].[PortalID] point to this entity (FK_TelavatRequests_Portals)
        /// </summary>
        public virtual ICollection<SamtRequest> SamtRequests { get; set; } // SAMT_Requests.FK_TelavatRequests_Portals

        /// <summary>
        /// Child ShiftEmploymentDetails where [Shift_EmploymentDetail].[portalId] point to this entity (FK_Shift_EmploymentDetail_Portals)
        /// </summary>
        public virtual ICollection<ShiftEmploymentDetail> ShiftEmploymentDetails { get; set; } // Shift_EmploymentDetail.FK_Shift_EmploymentDetail_Portals

        /// <summary>
        /// Child ShiftLocations where [Shift_Location].[PortalId] point to this entity (FK_Shift_Location_Portals)
        /// </summary>
        public virtual ICollection<ShiftLocation> ShiftLocations { get; set; } // Shift_Location.FK_Shift_Location_Portals

        /// <summary>
        /// Child ShiftShifts where [Shift_Shift].[PortalId] point to this entity (FK_PortalShift_Portals)
        /// </summary>
        public virtual ICollection<ShiftShift> ShiftShifts { get; set; } // Shift_Shift.FK_PortalShift_Portals

        /// <summary>
        /// Child TelavatAgentPosts where [TelavatAgentPosts].[PortalID] point to this entity (FK_TelavatAgentPosts_Portals)
        /// </summary>
        public virtual ICollection<TelavatAgentPost> TelavatAgentPosts { get; set; } // TelavatAgentPosts.FK_TelavatAgentPosts_Portals

        /// <summary>
        /// Child TelavatBandSounds where [TelavatBandSounds].[PortalID] point to this entity (FK_TelavatBandSounds_Portals)
        /// </summary>
        public virtual ICollection<TelavatBandSound> TelavatBandSounds { get; set; } // TelavatBandSounds.FK_TelavatBandSounds_Portals

        /// <summary>
        /// Child TelavatCategoryAges where [TelavatCategoryAges].[PortalID] point to this entity (FK_TelavatCategoryAges_Portals)
        /// </summary>
        public virtual ICollection<TelavatCategoryAge> TelavatCategoryAges { get; set; } // TelavatCategoryAges.FK_TelavatCategoryAges_Portals

        /// <summary>
        /// Child TelavatCertifications where [TelavatCertifications].[PortalID] point to this entity (FK_TelavatCertifications_Portals)
        /// </summary>
        public virtual ICollection<TelavatCertification> TelavatCertifications { get; set; } // TelavatCertifications.FK_TelavatCertifications_Portals

        /// <summary>
        /// Child TelavatPlayStatus where [TelavatPlayStatus].[PortalID] point to this entity (FK_TelavatPlayStatus_Portals)
        /// </summary>
        public virtual ICollection<TelavatPlayStatu> TelavatPlayStatus { get; set; } // TelavatPlayStatus.FK_TelavatPlayStatus_Portals

        /// <summary>
        /// Child TelavatProgramExperts where [TelavatProgramExperts].[PortalID] point to this entity (FK_TelavatProgramExperts_Portals)
        /// </summary>
        public virtual ICollection<TelavatProgramExpert> TelavatProgramExperts { get; set; } // TelavatProgramExperts.FK_TelavatProgramExperts_Portals

        /// <summary>
        /// Child TelavatProgramOccasions where [TelavatProgramOccasions].[PortalID] point to this entity (FK_TelavatProgramOccasions_Portals)
        /// </summary>
        public virtual ICollection<TelavatProgramOccasion> TelavatProgramOccasions { get; set; } // TelavatProgramOccasions.FK_TelavatProgramOccasions_Portals

        /// <summary>
        /// Child TelavatProgramTypes where [TelavatProgramTypes].[PortalID] point to this entity (FK_TelavatProgramTypes_Portals)
        /// </summary>
        public virtual ICollection<TelavatProgramType> TelavatProgramTypes { get; set; } // TelavatProgramTypes.FK_TelavatProgramTypes_Portals

        /// <summary>
        /// Child TelavatSourceTypes where [TelavatSourceTypes].[PortalID] point to this entity (FK_TelavatSourceTypes_Portals)
        /// </summary>
        public virtual ICollection<TelavatSourceType> TelavatSourceTypes { get; set; } // TelavatSourceTypes.FK_TelavatSourceTypes_Portals

        /// <summary>
        /// Child TelavatStructures where [TelavatStructures].[PortalID] point to this entity (FK_TelavatStructures_Portals)
        /// </summary>
        public virtual ICollection<TelavatStructure> TelavatStructures { get; set; } // TelavatStructures.FK_TelavatStructures_Portals

        /// <summary>
        /// Child TelavatSubsidiarySubjects where [TelavatSubsidiarySubjects].[PortalID] point to this entity (FK_TelavatSubsidiarySubjects_Portals)
        /// </summary>
        public virtual ICollection<TelavatSubsidiarySubject> TelavatSubsidiarySubjects { get; set; } // TelavatSubsidiarySubjects.FK_TelavatSubsidiarySubjects_Portals

        /// <summary>
        /// Child TelavatSubtitleStatus where [TelavatSubtitleStatus].[PortalID] point to this entity (FK_TelavatProgramSubtitles_Portals)
        /// </summary>
        public virtual ICollection<TelavatSubtitleStatu> TelavatSubtitleStatus { get; set; } // TelavatSubtitleStatus.FK_TelavatProgramSubtitles_Portals

        /// <summary>
        /// Child TelavatSuras where [TelavatSuras].[PortalID] point to this entity (FK_TelavatSuras_Portals)
        /// </summary>
        public virtual ICollection<TelavatSura> TelavatSuras { get; set; } // TelavatSuras.FK_TelavatSuras_Portals

        /// <summary>
        /// Child TelavatTopics where [TelavatTopics].[PortalID] point to this entity (FK_TelavatTopics_Portals)
        /// </summary>
        public virtual ICollection<TelavatTopic> TelavatTopics { get; set; } // TelavatTopics.FK_TelavatTopics_Portals

        /// <summary>
        /// Child Users where [Users].[PortalID] point to this entity (FK_Users_Portals)
        /// </summary>
        public virtual ICollection<User> Users { get; set; } // Users.FK_Users_Portals

        /// <summary>
        /// Child UsersPortals where [UsersPortals].[PortalId] point to this entity (FK_UsersPortals_Portals)
        /// </summary>
        public virtual ICollection<UsersPortal> UsersPortals { get; set; } // UsersPortals.FK_UsersPortals_Portals

        public Portal()
        {
            Domain = "";
            Description = "";
            Alias = "";
            Language = "fa";
            Favicon = "";
            ShowHerOwnLogo = false;
            NoDashboard = false;
            Qouta = 0;
            Ordering = 0;
            IsSelected = false;
            Enable = true;
            ChannelGroups = new List<ChannelGroup>();
            ConductorBroadcastCertificates = new List<ConductorBroadcastCertificate>();
            ConductorChannelProgramTags = new List<ConductorChannelProgramTag>();
            OldTelavatGrades2 = new List<OldTelavatGrades2>();
            PakhshChannelLocations = new List<PakhshChannelLocation>();
            PakhshChannelSettings = new List<PakhshChannelSetting>();
            PakhshManageShifts = new List<PakhshManageShift>();
            PakhshShiftSettings = new List<PakhshShiftSetting>();
            PortalAddresses = new List<PortalAddress>();
            RayanCounterOnlineUsers = new List<RayanCounterOnlineUser>();
            SamtGroups = new List<SamtGroup>();
            SamtMonthlyBudgets = new List<SamtMonthlyBudget>();
            SamtRequests = new List<SamtRequest>();
            ShiftEmploymentDetails = new List<ShiftEmploymentDetail>();
            ShiftLocations = new List<ShiftLocation>();
            ShiftShifts = new List<ShiftShift>();
            TelavatAgentPosts = new List<TelavatAgentPost>();
            TelavatBandSounds = new List<TelavatBandSound>();
            TelavatCategoryAges = new List<TelavatCategoryAge>();
            TelavatCertifications = new List<TelavatCertification>();
            TelavatPlayStatus = new List<TelavatPlayStatu>();
            TelavatProgramExperts = new List<TelavatProgramExpert>();
            TelavatProgramOccasions = new List<TelavatProgramOccasion>();
            TelavatProgramTypes = new List<TelavatProgramType>();
            TelavatSourceTypes = new List<TelavatSourceType>();
            TelavatStructures = new List<TelavatStructure>();
            TelavatSubsidiarySubjects = new List<TelavatSubsidiarySubject>();
            TelavatSubtitleStatus = new List<TelavatSubtitleStatu>();
            TelavatSuras = new List<TelavatSura>();
            TelavatTopics = new List<TelavatTopic>();
            Users = new List<User>();
            UsersPortals = new List<UsersPortal>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
