// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // ProcessStatus
    public partial class ProcessStatu
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public string TitleView { get; set; } // TitleView (length: 1000)
        public string FormKey { get; set; } // FormKey (length: 1000)
        public int Ordering { get; set; } // Ordering
        public int PortalId { get; set; } // PortalID
        public bool IsSelectable { get; set; } // IsSelectable
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child ConductorItemDispatches where [ConductorItemDispatch].[StatusId] point to this entity (FK_ConductorItemDispatch_ProcessStatus)
        /// </summary>
        public virtual ICollection<ConductorItemDispatch> ConductorItemDispatches { get; set; } // ConductorItemDispatch.FK_ConductorItemDispatch_ProcessStatus

        /// <summary>
        /// Child ConductorItemDispatchLogs where [ConductorItemDispatchLogs].[StatusID] point to this entity (FK_ConductorItemDispatchLogs_ProcessStatus)
        /// </summary>
        public virtual ICollection<ConductorItemDispatchLog> ConductorItemDispatchLogs { get; set; } // ConductorItemDispatchLogs.FK_ConductorItemDispatchLogs_ProcessStatus

        public ProcessStatu()
        {
            ConductorItemDispatches = new List<ConductorItemDispatch>();
            ConductorItemDispatchLogs = new List<ConductorItemDispatchLog>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
