// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // RayanLinkSelections
    public partial class RayanLinkSelection
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 50)
        public string TableName { get; set; } // TableName (length: 50)
        public string IdField { get; set; } // IDField (length: 50)
        public string ValueField { get; set; } // ValueField (length: 50)
        public string ModulekeyToSend { get; set; } // modulekeyToSend (length: 150)
        public string ImageFileUri { get; set; } // ImageFileURI (length: 150)
        public string Description { get; set; } // Description (length: 150)
        public bool IsPortalBase { get; set; } // IsPortalBase

        public RayanLinkSelection()
        {
            IsPortalBase = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
