// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_BaravordHistory
    public partial class SamtBaravordHistory
    {
        public int Id { get; set; } // ID (Primary key)
        public int RequestId { get; set; } // RequestID
        public int StatusId { get; set; } // StatusID
        public DateTime? CreationDateTime { get; set; } // CreationDateTime

        public SamtBaravordHistory()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
