// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_StructureTypes
    public partial class SamtStructureType
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int Ordering { get; set; } // Ordering
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child SamtProductionSettings where [SAMT_ProductionSettings].[StructureTypeID] point to this entity (FK_SAMT_ProductionSettings_SAMT_StructureTypes)
        /// </summary>
        public virtual ICollection<SamtProductionSetting> SamtProductionSettings { get; set; } // SAMT_ProductionSettings.FK_SAMT_ProductionSettings_SAMT_StructureTypes

        /// <summary>
        /// Child SamtRequests where [SAMT_Requests].[StructureTypeID] point to this entity (FK_TelavatRequests_TelavatStructureTypes)
        /// </summary>
        public virtual ICollection<SamtRequest> SamtRequests { get; set; } // SAMT_Requests.FK_TelavatRequests_TelavatStructureTypes

        public SamtStructureType()
        {
            IsDeleted = false;
            SamtProductionSettings = new List<SamtProductionSetting>();
            SamtRequests = new List<SamtRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
