// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_HistoryAgent
    public partial class SamtHistoryAgent
    {
        public int Id { get; set; } // ID (Primary key)
        public int AgentId { get; set; } // AgentID
        public int ResorceTypeId { get; set; } // ResorceTypeID
        public string Program { get; set; } // Program (length: 400)
        public string Year { get; set; } // Year (length: 4)
        public int? Evaluation { get; set; } // Evaluation
        public string Festival { get; set; } // Festival (length: 1000)
        public string Description { get; set; } // Description

        /// <summary>
        /// صفر سریال، یک فیلم سینمایی،دو جشنواره
        /// </summary>
        public int? Type { get; set; } // Type

        public SamtHistoryAgent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
