// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_ProposalGender
    public partial class SamtProposalGender
    {
        public int ProposalGenderId { get; set; } // ProposalGenderID (Primary key)
        public int? RequestId { get; set; } // RequestID
        public bool? Male { get; set; } // male
        public bool? Female { get; set; } // Female
        public bool? Sayer { get; set; } // Sayer

        public SamtProposalGender()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
