// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_ResourceCategoryType
    public partial class SamtResourceCategoryType
    {
        public int Id { get; set; } // ID (Primary key)
        public int ResourceCategoryId { get; set; } // ResourceCategoryID
        public int ResourceTypeId { get; set; } // ResourceTypeID
        public bool IsExpire { get; set; } // IsExpire

        public SamtResourceCategoryType()
        {
            IsExpire = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
