// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_RequestLogStatus
    public partial class SamtRequestLogStatu
    {
        public int Id { get; set; } // ID (Primary key)
        public int LogId { get; set; } // LogID
        public int Status { get; set; } // Status

        // Foreign keys

        /// <summary>
        /// Parent SamtRequestLog pointed by [SAMT_RequestLogStatus].([LogId]) (FK_TelavatRequestLogStatus_TelavatRequestLogs)
        /// </summary>
        public virtual SamtRequestLog SamtRequestLog { get; set; } // FK_TelavatRequestLogStatus_TelavatRequestLogs

        public SamtRequestLogStatu()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
