// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMTV3_ImportanceDegrees
    public partial class Samtv3ImportanceDegree
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 200)
        public int? ItemOrder { get; set; } // ItemOrder
        public bool IsActive { get; set; } // IsActive
        public int? CreatedBy { get; set; } // CreatedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child Samtv3Monitoring where [SAMTV3_Monitoring].[ImportanceId] point to this entity (FK_SAMTV3_Monitoring_SAMTV3_ImportanceDegrees)
        /// </summary>
        public virtual ICollection<Samtv3Monitoring> Samtv3Monitoring { get; set; } // SAMTV3_Monitoring.FK_SAMTV3_Monitoring_SAMTV3_ImportanceDegrees

        public Samtv3ImportanceDegree()
        {
            ItemOrder = 1;
            Samtv3Monitoring = new List<Samtv3Monitoring>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
