// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMTV3_MonitoringSubjects
    public partial class Samtv3MonitoringSubject
    {
        public int Id { get; set; } // ID (Primary key)
        public int MonitoringId { get; set; } // MonitoringId
        public int SubjectId { get; set; } // SubjectId
        public bool IsDeleted { get; set; } // IsDeleted
        public int? CreatedBy { get; set; } // CreatedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Foreign keys

        /// <summary>
        /// Parent SamtSubject pointed by [SAMTV3_MonitoringSubjects].([SubjectId]) (FK_SAMTV3_MonitoringSubjects_SAMT_Subjects)
        /// </summary>
        public virtual SamtSubject SamtSubject { get; set; } // FK_SAMTV3_MonitoringSubjects_SAMT_Subjects

        /// <summary>
        /// Parent Samtv3Monitoring pointed by [SAMTV3_MonitoringSubjects].([MonitoringId]) (FK_SAMTV3_MonitoringSubjects_SAMTV3_Monitoring)
        /// </summary>
        public virtual Samtv3Monitoring Samtv3Monitoring { get; set; } // FK_SAMTV3_MonitoringSubjects_SAMTV3_Monitoring

        public Samtv3MonitoringSubject()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
