// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_RequestAgents
    public partial class SamtRequestAgent
    {
        public int Id { get; set; } // ID (Primary key)
        public int RequestId { get; set; } // RequestID
        public int AgentId { get; set; } // AgentID
        public int ResourceTypeId { get; set; } // ResourceTypeID
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent SamtRequest pointed by [SAMT_RequestAgents].([RequestId]) (FK_TelavatRequestAgents_SAMT_Requests)
        /// </summary>
        public virtual SamtRequest SamtRequest { get; set; } // FK_TelavatRequestAgents_SAMT_Requests

        public SamtRequestAgent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
