// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_HRCooperationType
    public partial class SamtHrCooperationType
    {
        public int HrCooperationTypeId { get; set; } // HRCooperationTypeID (Primary key)
        public string HrCooperationTypeTitle { get; set; } // HRCooperationTypeTitle (length: 500)

        public SamtHrCooperationType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
