// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SAMT_BeforeProductions
    public partial class SamtBeforeProduction
    {
        public int Id { get; set; } // ID (Primary key)
        public int? ResearchProgress { get; set; } // ResearchProgress
        public string ResearchDescription { get; set; } // ResearchDescription (length: 2000)
        public int? WritingProgress { get; set; } // WritingProgress
        public int? WritingPart { get; set; } // WritingPart
        public string WritingDescription { get; set; } // WritingDescription (length: 2000)
        public int? LocationProgress { get; set; } // LocationProgress
        public string LocationDescription { get; set; } // LocationDescription (length: 2000)
        public int? AccessoryProgress { get; set; } // AccessoryProgress
        public string AccessoryDescription { get; set; } // AccessoryDescription (length: 2000)
        public int? DecorProgress { get; set; } // DecorProgress
        public string DecorDescription { get; set; } // DecorDescription (length: 2000)
        public int? MakeupProgress { get; set; } // MakeupProgress
        public string MakeupDescription { get; set; } // MakeupDescription (length: 2000)
        public int? ClothDesignProgress { get; set; } // ClothDesignProgress
        public string ClothDesignDescription { get; set; } // ClothDesignDescription (length: 2000)
        public int? TechnicalFactorsProgress { get; set; } // TechnicalFactorsProgress
        public int? ActorProgress { get; set; } // ActorProgress
        public int RequestId { get; set; } // RequestID
        public DateTime? CreateDate { get; set; } // CreateDate
        public DateTime? ModifyDate { get; set; } // ModifyDate
        public int? CreatorId { get; set; } // CreatorId

        // Reverse navigation

        /// <summary>
        /// Child SamtBeforeProductionAgents where [SAMT_BeforeProductionAgents].[BeforeProductionID] point to this entity (FK_SAMT_BeforeProductionAgents_SAMT_BeforeProductions)
        /// </summary>
        public virtual ICollection<SamtBeforeProductionAgent> SamtBeforeProductionAgents { get; set; } // SAMT_BeforeProductionAgents.FK_SAMT_BeforeProductionAgents_SAMT_BeforeProductions

        // Foreign keys

        /// <summary>
        /// Parent SamtRequest pointed by [SAMT_BeforeProductions].([RequestId]) (FK_SAMT_BeforeProductions_SAMT_Requests)
        /// </summary>
        public virtual SamtRequest SamtRequest { get; set; } // FK_SAMT_BeforeProductions_SAMT_Requests

        public SamtBeforeProduction()
        {
            SamtBeforeProductionAgents = new List<SamtBeforeProductionAgent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
