// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Shift_ShiftTabletConductor
    public partial class ShiftShiftTabletConductor
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ShiftTabletId { get; set; } // ShiftTabletId
        public string ConductorDate { get; set; } // ConductorDate (length: 50)

        public ShiftShiftTabletConductor()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
