// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Shift_PortalLocations
    public partial class ShiftPortalLocation
    {
        public int Id { get; set; } // ID (Primary key)
        public int LocationId { get; set; } // LocationID
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public int PortalId { get; set; } // PortalID
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [Shift_PortalLocations].([PortalId]) (FK_Shift_ShiftTabletLocation_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_Shift_ShiftTabletLocation_Portals

        /// <summary>
        /// Parent ShiftLocation pointed by [Shift_PortalLocations].([LocationId]) (FK_ShiftExecutionLocation_Location)
        /// </summary>
        public virtual ShiftLocation ShiftLocation { get; set; } // FK_ShiftExecutionLocation_Location

        public ShiftPortalLocation()
        {
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
