// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Shift_ShiftTablet
    public partial class ShiftShiftTablet
    {
        public int Id { get; set; } // ID (Primary key)
        public int? ShiftId { get; set; } // ShiftID
        public DateTime? ShiftDate { get; set; } // ShiftDate
        public int? ProductionTypeId { get; set; } // ProductionTypeId
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        /// <summary>
        /// ارزش درصدی شیفت که بر اساس روزهای خاص ثبت میشود.
        /// </summary>
        public int? ShiftWorthPercent { get; set; } // ShiftWorthPercent
        public TimeSpan? ShiftTime { get; set; } // ShiftTime
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ShiftShiftTabletCrews where [Shift_ShiftTabletCrew].[ShiftTabletId] point to this entity (FK_Shift_ShiftTableCrew_Shift_ShiftTablet)
        /// </summary>
        public virtual ICollection<ShiftShiftTabletCrew> ShiftShiftTabletCrews { get; set; } // Shift_ShiftTabletCrew.FK_Shift_ShiftTableCrew_Shift_ShiftTablet

        /// <summary>
        /// Child ShiftShiftTabletLocations where [Shift_ShiftTabletLocation].[ShiftTabletID] point to this entity (FK_ShiftExecutionLocation_ShiftExecution)
        /// </summary>
        public virtual ICollection<ShiftShiftTabletLocation> ShiftShiftTabletLocations { get; set; } // Shift_ShiftTabletLocation.FK_ShiftExecutionLocation_ShiftExecution

        // Foreign keys

        /// <summary>
        /// Parent ShiftProductionType pointed by [Shift_ShiftTablet].([ProductionTypeId]) (FK_ShiftExecution_ProductionType)
        /// </summary>
        public virtual ShiftProductionType ShiftProductionType { get; set; } // FK_ShiftExecution_ProductionType

        /// <summary>
        /// Parent ShiftShift pointed by [Shift_ShiftTablet].([ShiftId]) (FK_ShiftExecution_PortalShift)
        /// </summary>
        public virtual ShiftShift ShiftShift { get; set; } // FK_ShiftExecution_PortalShift

        public ShiftShiftTablet()
        {
            ShiftShiftTabletCrews = new List<ShiftShiftTabletCrew>();
            ShiftShiftTabletLocations = new List<ShiftShiftTabletLocation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
