// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Shift_ShiftTabletCrewReplacement
    public partial class ShiftShiftTabletCrewReplacement
    {
        public int Id { get; set; } // ID (Primary key)
        public int ShiftTabletCrewId { get; set; } // ShiftTabletCrewId
        public int ShiftTabletCrewIdReplaceMent { get; set; } // ShiftTabletCrewIdReplaceMent
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Foreign keys

        /// <summary>
        /// Parent ShiftShiftTabletCrew pointed by [Shift_ShiftTabletCrewReplacement].([ShiftTabletCrewIdReplaceMent]) (FK_Shift_ShiftTabletCrewReplacement_Shift_ShiftTabletCrew1)
        /// </summary>
        public virtual ShiftShiftTabletCrew ShiftShiftTabletCrew_ShiftTabletCrewIdReplaceMent { get; set; } // FK_Shift_ShiftTabletCrewReplacement_Shift_ShiftTabletCrew1

        /// <summary>
        /// Parent ShiftShiftTabletCrew pointed by [Shift_ShiftTabletCrewReplacement].([ShiftTabletCrewId]) (FK_Shift_ShiftTabletCrewReplacement_Shift_ShiftTabletCrew)
        /// </summary>
        public virtual ShiftShiftTabletCrew ShiftTabletCrew { get; set; } // FK_Shift_ShiftTabletCrewReplacement_Shift_ShiftTabletCrew

        public ShiftShiftTabletCrewReplacement()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
