// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Shift_Locations
    public partial class ShiftLocation
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 250)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ShiftPortalLocations where [Shift_PortalLocations].[LocationID] point to this entity (FK_ShiftExecutionLocation_Location)
        /// </summary>
        public virtual ICollection<ShiftPortalLocation> ShiftPortalLocations { get; set; } // Shift_PortalLocations.FK_ShiftExecutionLocation_Location

        public ShiftLocation()
        {
            IsDeleted = false;
            ShiftPortalLocations = new List<ShiftPortalLocation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
