// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // SIMA_Requests
    public partial class SimaRequest
    {
        public int RequestId { get; set; } // RequestID (Primary key)
        public string BaseYear { get; set; } // BaseYear (length: 5)
        public string Program { get; set; } // Program (length: 350)
        public int? PortalId { get; set; } // PortalID
        public int? GroupId { get; set; } // GroupID
        public string LicenseNumber { get; set; } // LicenseNumber (length: 17)
        public string ExportationDate { get; set; } // ExportationDate (length: 10)
        public int? ProgramGradeId { get; set; } // ProgramGradeID
        public int? StructureId { get; set; } // StructureID
        public int? SubStructureId { get; set; } // SubStructureID
        public int? LicenseProgramCount { get; set; } // LicenseProgramCount
        public int? TotalTimeMin { get; set; } // TotalTimeMin
        public string ApprovedStartDate { get; set; } // ApprovedStartDate (length: 10)
        public string ApprovedEndDate { get; set; } // ApprovedEndDate (length: 10)
        public string ApprovedBroadCastDate { get; set; } // ApprovedBroadCastDate (length: 10)
        public int? StructureTypeId { get; set; } // StructureTypeID
        public int? ArchivedPercent { get; set; } // ArchivedPercent
        public int? RecordedPercent { get; set; } // RecordedPercent
        public int? LivePercent { get; set; } // LivePercent
        public string EstimateDate { get; set; } // EstimateDate (length: 10)
        public string EstimateNumer { get; set; } // EstimateNumer (length: 20)
        public int? ProgramNumber { get; set; } // ProgramNumber
        public int? Time { get; set; } // Time
        public double? MinuteRate { get; set; } // MinuteRate
        public double? DirectPayment { get; set; } // DirectPayment
        public string OtherDesc { get; set; } // OtherDesc
        public int? EvaluationType { get; set; } // EvaluationType
        public string TheParticipation { get; set; } // TheParticipation (length: 500)
        public int? NumberParticipation { get; set; } // NumberParticipation
        public bool? HasRevisoryEstimation { get; set; } // HasRevisoryEstimation
        public string CorrectiveDesc { get; set; } // CorrectiveDesc
        public string EvaluationEstimateDate { get; set; } // EvaluationEstimateDate (length: 10)
        public int? EvaluationProgramNumber { get; set; } // evaluationProgramNumber
        public int? EvaluationTime { get; set; } // EvaluationTime
        public double? EvaluationMinuteRate { get; set; } // EvaluationMinuteRate
        public double? EvaluationDirectPayment { get; set; } // EvaluationDirectPayment
        public string EvaluationDesc { get; set; } // EvaluationDesc
        public int? EvaluatedNumberPartnership { get; set; } // EvaluatedNumberPartnership
        public string EvaluatedThePartnership { get; set; } // EvaluatedThePartnership (length: 500)
        public string LastEstimateDate { get; set; } // LastEstimateDate (length: 10)
        public string Audience { get; set; } // Audience
        public int? PresentationTypeId { get; set; } // PresentationTypeID
        public bool? HasProposalHistory { get; set; } // HasProposalHistory
        public int? SubProposalHistoryId { get; set; } // SubProposalHistoryID
        public string ProposalBackground { get; set; } // ProposalBackground
        public string ProposalNecessary { get; set; } // ProposalNecessary
        public string ProposalGoals { get; set; } // ProposalGoals
        public bool? BroeadcastMorning { get; set; } // BroeadcastMorning
        public bool? BroeadcastNone { get; set; } // BroeadcastNone
        public bool? BroeadcastEvening { get; set; } // BroeadcastEvening
        public bool? BroeadcastNight { get; set; } // BroeadcastNight
        public bool? BroeadcastMidnight { get; set; } // BroeadcastMidnight
        public int? BroeadcastDurationId { get; set; } // BroeadcastDurationID
        public bool? Repeat { get; set; } // Repeat
        public int? SubRepeatId { get; set; } // SubRepeatID
        public bool? HasResearch { get; set; } // HasResearch

        public SimaRequest()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
