// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpByTagSubjectReportReturnModel
    {
        public int? RequestId { get; set; }
        public string Program { get; set; }
        public string EstimateNumer { get; set; }
        public string chName { get; set; }
        public string GroupName { get; set; }
        public int? PortalID { get; set; }
        public string Producer { get; set; }
        public string GradeTitle { get; set; }
        public string STitle { get; set; }
        public bool? isTransfered { get; set; }
        public int requestId1 { get; set; }
        public int? TotalFinalCount { get; set; }
        public int? TotalFinalTime { get; set; }
        public int? GroupProductionCount { get; set; }
        public int? GroupProductionTime { get; set; }
        public int? GroupReviewCount { get; set; }
        public int? GroupReviewTime { get; set; }
        public int? PlaybackCount { get; set; }
        public int? PlaybackTime { get; set; }
        public int? PlaybackReviewCount { get; set; }
        public int? PlaybackReviewTime { get; set; }
    }

}
// </auto-generated>
