// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpByEstimateOutlineReturnModel
    {
        public string Program { get; set; }
        public string chName { get; set; }
        public string GroupName { get; set; }
        public int? ChannelId { get; set; }
        public string EstimateNumer { get; set; }
        public string GradeTitle { get; set; }
        public string STitle { get; set; }
        public int? ClacketCount { get; set; }
        public int? TotalMinutes { get; set; }
        public bool? estimationType { get; set; }
        public string EstimateDate { get; set; }
        public string Producer { get; set; }
        public int? ApproachId { get; set; }
        public bool? isTransfered { get; set; }
        public double? TotalPayment { get; set; }
        public double? ParticipationPercent { get; set; }
        public string TheParticipation { get; set; }
        public string MosharekatName { get; set; }
        public double? ParticipantAmount { get; set; }
        public int? BaravordStatus { get; set; }
        public double? ClacketTime { get; set; }
        public double? MinutePrice { get; set; }
    }

}
// </auto-generated>
