// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpBySubjectPercentReturnModel
    {
        public int? Level1 { get; set; }
        public int? Level2 { get; set; }
        public string MainSubjectTitle { get; set; }
        public string SubjectTitle { get; set; }
        public int? AverageBaravord { get; set; }
        public int? BaravordTotalLevel2 { get; set; }
        public int? BaravordTotalLevel1 { get; set; }
        public int? BaravordPercented { get; set; }
        public int? BaravordPercentedTotal { get; set; }
        public int? AverageTarh { get; set; }
        public int? TarhTotalLevel2 { get; set; }
        public int? TarhTotalLevel1 { get; set; }
        public int? TarhPercented { get; set; }
        public int? TarhPercentedTotal { get; set; }
        public int? AverageProduction { get; set; }
        public int? ProductionTotalLevel2 { get; set; }
        public int? ProductionTotalLevel1 { get; set; }
        public int? ProductionPercented { get; set; }
        public int? ProductionPercentedTotal { get; set; }
    }

}
// </auto-generated>
