// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpChanelsParticipationReturnModel
    {
        public int? PortalID { get; set; }
        public double? PayedMosharekat { get; set; }
        public long? AllPayment { get; set; }
        public double? diff { get; set; }
        public string ChannelName { get; set; }
    }

}
// </auto-generated>
