// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpChannelsApproachReturnModel
    {
        public string Title { get; set; }
        public int? MosavabTime { get; set; }
        public int? TotalMosavab { get; set; }
        public int? BaravordTime { get; set; }
        public int? TotalBaravord { get; set; }
        public int? TolidTime { get; set; }
        public int? TotalTolid { get; set; }
    }

}
// </auto-generated>
