// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpDetailEventReportReturnModel
    {
        public string Program { get; set; }
        public string LicenseNumber { get; set; }
        public int? Column1 { get; set; }
        public string Portal { get; set; }
        public int? Column2 { get; set; }
        public string GroupTitle { get; set; }
        public int? BaseYearCount { get; set; }
        public int? BaseYearTime { get; set; }
        public int? Column3 { get; set; }
        public string Structure { get; set; }
        public int? Column4 { get; set; }
        public string Grade { get; set; }
        public int? Column5 { get; set; }
        public string StructureType { get; set; }
    }

}
// </auto-generated>
