// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpGetPlanTopicsHierarchyReturnModel
    {
        public int? id { get; set; }
        public int? parentId { get; set; }
        public string Title { get; set; }
        public int? Grade { get; set; }
        public bool? IsActive { get; set; }
        public string ParentTitle { get; set; }
    }

}
// </auto-generated>
