// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpGetConductorByProgramIdReturnModel
    {
        public string Title { get; set; }
        public string BroadcastDate { get; set; }
        public int versionnumber { get; set; }
        public string ProgramLength { get; set; }
        public string BroadcastTime { get; set; }
        public string Part { get; set; }
        public bool isLive { get; set; }
        public bool isRepeat { get; set; }
        public string Description { get; set; }
        public int ChannelID { get; set; }
    }

}
// </auto-generated>
