// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpGetPakhshProgramReportReturnModel
    {
        public int ID { get; set; }
        public string TypeLabel { get; set; }
        public string TitleLabel { get; set; }
        public string WhichLabel { get; set; }
        public int? WhichValue { get; set; }
        public int? TotalCount { get; set; }
        public int? TotalDurationSeconds { get; set; }
        public string TotalDuration { get; set; }
    }

}
// </auto-generated>
