// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpGetProgramDetailReturnModel
    {
        public int ProgramID { get; set; }
        public string ProgramTitle { get; set; }
        public string CountryProducer { get; set; }
        public string ProductionYear { get; set; }
        public string ProductionTypeTitle { get; set; }
        public int? ProductionType { get; set; }
        public string BroadcastTypeTitle { get; set; }
        public int? BroadcastType { get; set; }
        public string PreparationTypeTitle { get; set; }
        public int? PreparationType { get; set; }
        public string StructureTitle { get; set; }
        public int? StructureID { get; set; }
        public string SubStructureTitle { get; set; }
        public int? SubStructureID { get; set; }
        public string ProgramProducer { get; set; }
        public string EventTitle { get; set; }
        public int ClacketCount { get; set; }
    }

}
// </auto-generated>
