// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SplitReturnModel
    {
        public string val { get; set; }
    }

}
// </auto-generated>
