// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpMojriActivityReturnModel
    {
        public class ResultSetModel1
        {
            public int? PortalID { get; set; }
            public string Portal { get; set; }
            public int? CountMojriID { get; set; }
        }
        public List<ResultSetModel1> ResultSet1;
        public class ResultSetModel2
        {
            public int? PortalID { get; set; }
            public string Portal { get; set; }
            public int? CountMojriID { get; set; }
        }
        public List<ResultSetModel2> ResultSet2;
        public class ResultSetModel3
        {
            public int? PortalID { get; set; }
            public string Portal { get; set; }
            public int? CountMojriID { get; set; }
        }
        public List<ResultSetModel3> ResultSet3;
    }

}
// </auto-generated>
