// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpMojriActivityDetailReturnModel
    {
        public class ResultSetModel1
        {
            public int? MojriID { get; set; }
            public string FullName { get; set; }
            public string NationalCode { get; set; }
            public string BirthDate { get; set; }
            public string EmployeeNum { get; set; }
            public string EducationDegree { get; set; }
            public string EducationField { get; set; }
            public string EducationPlace { get; set; }
            public string Phone { get; set; }
            public string Mobile { get; set; }
        }
        public List<ResultSetModel1> ResultSet1;
        public class ResultSetModel2
        {
            public int? MojriID { get; set; }
            public string FullName { get; set; }
            public string NationalCode { get; set; }
            public string BirthDate { get; set; }
            public string EmployeeNum { get; set; }
            public string EducationDegree { get; set; }
            public string EducationField { get; set; }
            public string EducationPlace { get; set; }
            public string Phone { get; set; }
            public string Mobile { get; set; }
        }
        public List<ResultSetModel2> ResultSet2;
        public class ResultSetModel3
        {
            public int? MojriID { get; set; }
            public string FullName { get; set; }
            public string NationalCode { get; set; }
            public string BirthDate { get; set; }
            public string EmployeeNum { get; set; }
            public string EducationDegree { get; set; }
            public string EducationField { get; set; }
            public string EducationPlace { get; set; }
            public string Phone { get; set; }
            public string Mobile { get; set; }
        }
        public List<ResultSetModel3> ResultSet3;
    }

}
// </auto-generated>
