// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpProductionProgressByRequestIdReturnModel
    {
        public int ID { get; set; }
        public int RequestProductionID { get; set; }
        public int RequestID { get; set; }
        public int SettingItemID { get; set; }
        public int? Value { get; set; }
        public int? FieldType { get; set; }
    }

}
// </auto-generated>
