// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpProgramSubjectsReturnModel
    {
        public class ResultSetModel1
        {
            public long? RowNo { get; set; }
            public int? ID { get; set; }
            public int SubjectID3 { get; set; }
            public int SubjectLevel3 { get; set; }
            public string Title3 { get; set; }
            public int? SubjectPercent3 { get; set; }
            public int SubjectID2 { get; set; }
            public int SubjectLevel2 { get; set; }
            public string Title2 { get; set; }
            public int SubjectID1 { get; set; }
            public int SubjectLevel1 { get; set; }
            public string Title1 { get; set; }
            public int PortalID { get; set; }
            public string Program { get; set; }
            public string ChannelName { get; set; }
            public string GroupTitle { get; set; }
            public string LicenseNumber { get; set; }
            public string EstimateNumer { get; set; }
            public string GradeTitle { get; set; }
            public int? BaseYearTime { get; set; }
            public int? BaseYearCount { get; set; }
            public int? BaseYearClacketTime { get; set; }
            public int? LicenseProgramTime { get; set; }
            public int? LicenseCount { get; set; }
            public int? LicenseClacketTime { get; set; }
            public string StructureTitle { get; set; }
            public string Producer { get; set; }
            public bool? isTransfered { get; set; }
            public int BaseYear { get; set; }
        }
        public List<ResultSetModel1> ResultSet1;
        public class ResultSetModel2
        {
            public long? RowNo { get; set; }
            public int? ID { get; set; }
            public int SubjectID3 { get; set; }
            public int SubjectLevel3 { get; set; }
            public string Title3 { get; set; }
            public int? SubjectPercent3 { get; set; }
            public int SubjectID2 { get; set; }
            public int SubjectLevel2 { get; set; }
            public string Title2 { get; set; }
            public int SubjectID1 { get; set; }
            public int SubjectLevel1 { get; set; }
            public string Title1 { get; set; }
            public int PortalID { get; set; }
            public string Program { get; set; }
            public string ChannelName { get; set; }
            public string GroupTitle { get; set; }
            public string LicenseNumber { get; set; }
            public string EstimateNumer { get; set; }
            public string GradeTitle { get; set; }
            public int? BaseYearTime { get; set; }
            public int? BaseYearCount { get; set; }
            public int? BaseYearClacketTime { get; set; }
            public int? LicenseProgramTime { get; set; }
            public int? LicenseCount { get; set; }
            public int? LicenseClacketTime { get; set; }
            public string StructureTitle { get; set; }
            public string Producer { get; set; }
            public bool? isTransfered { get; set; }
            public int BaseYear { get; set; }
        }
        public List<ResultSetModel2> ResultSet2;
    }

}
// </auto-generated>
