// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpProgramParticipationReturnModel
    {
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public string Program { get; set; }
        public int ID { get; set; }
        public int? PercentMosharekat { get; set; }
        public long? MosharekatAmount { get; set; }
        public long? BaseYearPayment { get; set; }
    }

}
// </auto-generated>
