// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpQualityByPortalReturnModel
    {
        public string Title { get; set; }
        public int PortalID { get; set; }
        public double? AvgProductionWeights { get; set; }
        public double? AvgTechniaclWeights { get; set; }
    }

}
// </auto-generated>
