// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpSamtRunTimeChanelsReturnModel
    {
        public int? ID { get; set; }
        public string Title { get; set; }
        public string ParentTitle { get; set; }
        public int? ParentID { get; set; }
        public int? Grade { get; set; }
        public int? TimeID { get; set; }
        public bool? IsActive { get; set; }
        public int? OrderID { get; set; }
    }

}
// </auto-generated>
