// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpShiftGetShiftByPortalIdReturnModel
    {
        public string PortalName { get; set; }
        public string Title { get; set; }
        public int PortalId { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int ShiftType { get; set; }
        public bool HasRewardFine { get; set; }
        public int RewarFineAmount { get; set; }
    }

}
// </auto-generated>
