// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Leopard.Repository
{
    public partial class SpUserHitReportReturnModel
    {
        public string uName { get; set; }
        public int? loginCount { get; set; }
        public int? ViewCount { get; set; }
        public string chName { get; set; }
        public DateTime? LastLogin { get; set; }
        public double? avgView { get; set; }
    }

}
// </auto-generated>
