// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatAgentPosts
    public partial class TelavatAgentPost
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering
        public double AmountWage { get; set; } // AmountWage
        public bool IsSecretaryScene { get; set; } // IsSecretaryScene

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [TelavatAgentPosts].([PortalId]) (FK_TelavatAgentPosts_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_TelavatAgentPosts_Portals

        public TelavatAgentPost()
        {
            AmountWage = 0;
            IsSecretaryScene = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
