// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatWorkTypes
    public partial class TelavatWorkType
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        public TelavatWorkType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
