// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatProgramStepPermissions
    public partial class TelavatProgramStepPermission
    {
        public int Id { get; set; } // ID (Primary key)
        public int StepId { get; set; } // StepID
        public int AssociatedStepId { get; set; } // AssociatedStepID
        public bool HasPermission { get; set; } // HasPermission

        public TelavatProgramStepPermission()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
