// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatRequestsConditions
    public partial class TelavatRequestsCondition
    {
        public int RequestId { get; set; } // RequestID (Primary key)
        public int ConditionId { get; set; } // ConditionID (Primary key)

        public TelavatRequestsCondition()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
