// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatPlaybackObserverReports
    public partial class TelavatPlaybackObserverReport
    {
        public int Id { get; set; } // ID (Primary key)
        public int LogId { get; set; } // LogID
        public string PlayDate { get; set; } // PlayDate (length: 10)
        public string PlayStartTime { get; set; } // PlayStartTime (length: 5)
        public string PlayEndTime { get; set; } // PlayEndTime (length: 5)
        public string Subject { get; set; } // Subject (length: 4000)
        public string Presenter { get; set; } // Presenter (length: 1000)
        public string Expert { get; set; } // Expert (length: 1000)
        public string DirectGuest { get; set; } // DirectGuest (length: 1000)
        public string PhoneGuest { get; set; } // PhoneGuest (length: 1000)
        public string Observer { get; set; } // Observer (length: 1000)
        public string Problems { get; set; } // Problems (length: 4000)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Foreign keys

        /// <summary>
        /// Parent SamtRequestLog pointed by [TelavatPlaybackObserverReports].([LogId]) (FK_TelavatPlaybackObserverReports_TelavatRequestLogs)
        /// </summary>
        public virtual SamtRequestLog SamtRequestLog { get; set; } // FK_TelavatPlaybackObserverReports_TelavatRequestLogs

        public TelavatPlaybackObserverReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
