// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatContentPriority
    public partial class TelavatContentPriority
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        // Reverse navigation

        /// <summary>
        /// Child SamtRequests where [SAMT_Requests].[ContentPriorityID] point to this entity (FK_TelavatRequests_TelavatContentPriority)
        /// </summary>
        public virtual ICollection<SamtRequest> SamtRequests { get; set; } // SAMT_Requests.FK_TelavatRequests_TelavatContentPriority

        public TelavatContentPriority()
        {
            PortalId = 1;
            Ordering = 1;
            SamtRequests = new List<SamtRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
