// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatTopics
    public partial class TelavatTopic
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [TelavatTopics].([PortalId]) (FK_TelavatTopics_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_TelavatTopics_Portals

        public TelavatTopic()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
