// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatSubtitleStatus
    public partial class TelavatSubtitleStatu
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        // Reverse navigation

        /// <summary>
        /// Child TelavatProgramVideos where [TelavatProgramVideos].[SubtitleStatusID] point to this entity (FK_TelavatProgramVideos_TelavatSubtitleStatus)
        /// </summary>
        public virtual ICollection<TelavatProgramVideo> TelavatProgramVideos { get; set; } // TelavatProgramVideos.FK_TelavatProgramVideos_TelavatSubtitleStatus

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [TelavatSubtitleStatus].([PortalId]) (FK_TelavatProgramSubtitles_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_TelavatProgramSubtitles_Portals

        public TelavatSubtitleStatu()
        {
            TelavatProgramVideos = new List<TelavatProgramVideo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
