// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatPlayStatus
    public partial class TelavatPlayStatu
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        // Reverse navigation

        /// <summary>
        /// Child TelavatProgramVideos where [TelavatProgramVideos].[PlayStatusID] point to this entity (FK_TelavatProgramVideos_TelavatPlayStatus)
        /// </summary>
        public virtual ICollection<TelavatProgramVideo> TelavatProgramVideos { get; set; } // TelavatProgramVideos.FK_TelavatProgramVideos_TelavatPlayStatus

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [TelavatPlayStatus].([PortalId]) (FK_TelavatPlayStatus_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_TelavatPlayStatus_Portals

        public TelavatPlayStatu()
        {
            TelavatProgramVideos = new List<TelavatProgramVideo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
