// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatHumanOutNeeds
    public partial class TelavatHumanOutNeed
    {
        public int Id { get; set; } // ID (Primary key)
        public int UnitId { get; set; } // UnitID
        public int RequestId { get; set; } // RequestID
        public int Count { get; set; } // Count
        public int? SubCount { get; set; } // SubCount
        public int? FeeType { get; set; } // FeeType
        public double? EstimatedFee { get; set; } // EstimatedFee
        public double? EvaluatedFee { get; set; } // EvaluatedFee
        public string JobTitle { get; set; } // JobTitle (length: 1000)
        public string Remarks { get; set; } // Remarks
        public bool IsDeleted { get; set; } // IsDeleted
        public double Fee { get; set; } // Fee

        // Foreign keys

        /// <summary>
        /// Parent TelavatUnit pointed by [TelavatHumanOutNeeds].([UnitId]) (FK_TelavatHumanOutNeeds_TelavatUnits)
        /// </summary>
        public virtual TelavatUnit TelavatUnit { get; set; } // FK_TelavatHumanOutNeeds_TelavatUnits

        public TelavatHumanOutNeed()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
