// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatSmsLogs
    public partial class TelavatSmsLog
    {
        public int Id { get; set; } // ID (Primary key)
        public int Type { get; set; } // Type
        public int ItemId { get; set; } // ItemID
        public string Mobile { get; set; } // Mobile (length: 20)
        public long Status { get; set; } // Status
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        public TelavatSmsLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
