// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatProgramOccasions
    public partial class TelavatProgramOccasion
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public int PortalId { get; set; } // PortalID
        public int Ordering { get; set; } // Ordering

        // Reverse navigation

        /// <summary>
        /// Child TelavatProgramVideos where [TelavatProgramVideos].[ProgramOccasionID] point to this entity (FK_TelavatProgramVideos_TelavatProgramOccasions)
        /// </summary>
        public virtual ICollection<TelavatProgramVideo> TelavatProgramVideos { get; set; } // TelavatProgramVideos.FK_TelavatProgramVideos_TelavatProgramOccasions

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [TelavatProgramOccasions].([PortalId]) (FK_TelavatProgramOccasions_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_TelavatProgramOccasions_Portals

        public TelavatProgramOccasion()
        {
            TelavatProgramVideos = new List<TelavatProgramVideo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
