// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // TelavatStatusPermissions
    public partial class TelavatStatusPermission
    {
        public int Id { get; set; } // ID (Primary key)
        public int StatusId { get; set; } // StatusID
        public int AssociatedStatusId { get; set; } // AssociatedStatusID
        public bool HasPermission { get; set; } // HasPermission

        // Foreign keys

        /// <summary>
        /// Parent TelavatStatus pointed by [TelavatStatusPermissions].([StatusId]) (FK_TelavatStatusPermissions_TelavatStatuses)
        /// </summary>
        public virtual TelavatStatus TelavatStatus { get; set; } // FK_TelavatStatusPermissions_TelavatStatuses

        public TelavatStatusPermission()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
