// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // Themes
    public partial class Theme
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public string ThemePath { get; set; } // ThemePath (length: 4000)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public string IconPicture { get; set; } // IconPicture (length: 150)
        public int PortalId { get; set; } // PortalId

        public Theme()
        {
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            IconPicture = "";
            PortalId = 1;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
