// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // UserProfileControls
    public partial class UserProfileControl
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 200)
        public string FilePath { get; set; } // FilePath (length: 1000)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime

        // Reverse navigation

        /// <summary>
        /// Child UserProfiles where [UserProfiles].[ProfileControlID] point to this entity (FK_UserProfiles_UserProfileControls)
        /// </summary>
        public virtual ICollection<UserProfile> UserProfiles { get; set; } // UserProfiles.FK_UserProfiles_UserProfileControls

        public UserProfileControl()
        {
            CreateDateTime = DateTime.Now;
            LastModifiedDateTime = DateTime.Now;
            UserProfiles = new List<UserProfile>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
