// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // UserUserTypeGroups
    public partial class UserUserTypeGroup
    {
        public int UserId { get; set; } // UserID (Primary key)
        public int UserTypeGroupId { get; set; } // UserTypeGroupID (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent UserTypeGroup pointed by [UserUserTypeGroups].([UserTypeGroupId]) (FK_UserUserTypeGroup_UserTypeGroups)
        /// </summary>
        public virtual UserTypeGroup UserTypeGroup { get; set; } // FK_UserUserTypeGroup_UserTypeGroups

        public UserUserTypeGroup()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
