// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // V_Albums
    public partial class VAlbum
    {
        public int Id { get; set; } // ID
        public string Title { get; set; } // Title (length: 101)
        public int PortalId { get; set; } // PortalID

        public VAlbum()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
