// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    // VW_SAMT_BaseLog
    public partial class VwSamtBaseLog
    {
        public int? RequestId { get; set; } // RequestID
        public double? Time { get; set; } // Time
        public int BaseYear { get; set; } // BaseYear
        public int PortalId { get; set; } // PortalID

        public VwSamtBaseLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
