// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace Shift.Repository
{
    public partial class ShiftDbContextFactory : IDesignTimeDbContextFactory<ShiftDbContext>
    {
        public ShiftDbContext CreateDbContext(string[] args)
        {
            return new ShiftDbContext();
        }
    }
}
// </auto-generated>
