// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    // SAMT_HRCooperationType
    public partial class SamtHrCooperationType
    {
        public int HrCooperationTypeId { get; set; } // HRCooperationTypeID (Primary key)
        public string HrCooperationTypeTitle { get; set; } // HRCooperationTypeTitle (length: 500)

        // Reverse navigation

        /// <summary>
        /// Child ShiftEmploymentDetails where [Shift_EmploymentDetail].[CooperationTypeID] point to this entity (FK_Shift_EmploymentDetail_SAMT_HRCooperationType)
        /// </summary>
        public virtual ICollection<ShiftEmploymentDetail> ShiftEmploymentDetails { get; set; } // Shift_EmploymentDetail.FK_Shift_EmploymentDetail_SAMT_HRCooperationType

        public SamtHrCooperationType()
        {
            ShiftEmploymentDetails = new List<ShiftEmploymentDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
