// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    // Shift_CrewRewardFine
    public partial class ShiftCrewRewardFine
    {
        public int Id { get; set; } // ID (Primary key)
        public int ShiftTabletCrewId { get; set; } // ShiftTabletCrewId
        public bool IsReward { get; set; } // IsReward
        public int Shiftpercentage { get; set; } // Shiftpercentage
        public int Ammount { get; set; } // Ammount
        public string Description { get; set; } // description (length: 500)
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ShiftCrewRewardFineReasons where [Shift_CrewRewardFineReason].[Shift_CrewRewardFineID] point to this entity (FK_Shift_CrewRewardFineReason_Shift_CrewRewardFine)
        /// </summary>
        public virtual ICollection<ShiftCrewRewardFineReason> ShiftCrewRewardFineReasons { get; set; } // Shift_CrewRewardFineReason.FK_Shift_CrewRewardFineReason_Shift_CrewRewardFine

        // Foreign keys

        /// <summary>
        /// Parent ShiftShiftTabletCrew pointed by [Shift_CrewRewardFine].([ShiftTabletCrewId]) (FK_Shift_CrewRewardFine_Shift_ShiftTabletCrew)
        /// </summary>
        public virtual ShiftShiftTabletCrew ShiftShiftTabletCrew { get; set; } // FK_Shift_CrewRewardFine_Shift_ShiftTabletCrew

        public ShiftCrewRewardFine()
        {
            ShiftCrewRewardFineReasons = new List<ShiftCrewRewardFineReason>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
