// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    // Shift_ShiftTemplate
    public partial class ShiftShiftTemplate
    {
        public int Id { get; set; } // ID (Primary key)
        public int JobId { get; set; } // JobID
        public int ShiftId { get; set; } // ShiftID
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent SamtResourceType pointed by [Shift_ShiftTemplate].([JobId]) (FK_ShiftNeededResource_SAMT_ResourceTypes)
        /// </summary>
        public virtual SamtResourceType SamtResourceType { get; set; } // FK_ShiftNeededResource_SAMT_ResourceTypes

        /// <summary>
        /// Parent ShiftShift pointed by [Shift_ShiftTemplate].([ShiftId]) (FK_ShiftNeededResource_Shift_Shift)
        /// </summary>
        public virtual ShiftShift ShiftShift { get; set; } // FK_ShiftNeededResource_Shift_Shift

        public ShiftShiftTemplate()
        {
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
