// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Shift.Repository
{
    // Shift_ShiftTabletPayments
    public partial class ShiftShiftTabletPayment
    {
        public int Id { get; set; } // ID (Primary key)
        public int AgentId { get; set; } // AgentID
        public int PortalId { get; set; } // PortalID
        public DateTime DateFrom { get; set; } // DateFrom
        public DateTime DateTo { get; set; } // DateTo
        public int YearPersian { get; set; } // YearPersian
        public int MonthPersian { get; set; } // MonthPersian
        public int? MandatoryShiftCount { get; set; } // MandatoryShiftCount
        public int NonMandatoryShiftCount { get; set; } // NonMandatoryShiftCount
        public decimal CalculatedPayment { get; set; } // CalculatedPayment
        public decimal? FinalPayment { get; set; } // FinalPayment
        public int? CreatedBy { get; set; } // CreatedBy
        public int? ModifiedBy { get; set; } // ModifiedBy
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public DateTime? LastModifiedDateTime { get; set; } // LastModifiedDateTime
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Portal pointed by [Shift_ShiftTabletPayments].([PortalId]) (FK_Shift_ShiftTabletPayments_Portals)
        /// </summary>
        public virtual Portal Portal { get; set; } // FK_Shift_ShiftTabletPayments_Portals

        /// <summary>
        /// Parent SamtAgent pointed by [Shift_ShiftTabletPayments].([AgentId]) (FK_Shift_ShiftTabletPayments_SAMT_Agents)
        /// </summary>
        public virtual SamtAgent SamtAgent { get; set; } // FK_Shift_ShiftTabletPayments_SAMT_Agents

        public ShiftShiftTabletPayment()
        {
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
