// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Shift.Repository
{
    public partial class SpShiftCheckShiftTimeOverlapReturnModel
    {
        public bool? checkOverlap { get; set; }
    }

}
// </auto-generated>
