// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // AdvertiseCategories
    public partial class AdvertiseCategoryConfiguration : IEntityTypeConfiguration<AdvertiseCategory>
    {
        public void Configure(EntityTypeBuilder<AdvertiseCategory> builder)
        {
            builder.ToTable("AdvertiseCategories", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_AdvertiseCategory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<AdvertiseCategory> builder);
    }

}
// </auto-generated>
