// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ClientSecrets
    public partial class ClientSecretConfiguration : IEntityTypeConfiguration<ClientSecret>
    {
        public void Configure(EntityTypeBuilder<ClientSecret> builder)
        {
            builder.ToTable("ClientSecrets", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ClientSecrets").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ClientId).HasColumnName(@"ClientId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar(4000)").IsRequired().HasMaxLength(4000);
            builder.Property(x => x.Expiration).HasColumnName(@"Expiration").HasColumnType("datetime2").IsRequired(false);
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar(250)").IsRequired().HasMaxLength(250);
            builder.Property(x => x.Created).HasColumnName(@"Created").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Client).WithMany(b => b.ClientSecrets).HasForeignKey(c => c.ClientId).HasConstraintName("FK_ClientSecrets_Clients_ClientId");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ClientSecret> builder);
    }

}
// </auto-generated>
