// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorChannelProgramAgents
    public partial class ConductorChannelProgramAgentConfiguration : IEntityTypeConfiguration<ConductorChannelProgramAgent>
    {
        public void Configure(EntityTypeBuilder<ConductorChannelProgramAgent> builder)
        {
            builder.ToTable("ConductorChannelProgramAgents", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorChannelProgramAgents").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ChannelProgramId).HasColumnName(@"ChannelProgramID").HasColumnType("int").IsRequired();
            builder.Property(x => x.AgentId).HasColumnName(@"AgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ResourceTypeId).HasColumnName(@"ResourceTypeID").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.ConductorChannelProgram).WithMany(b => b.ConductorChannelProgramAgents).HasForeignKey(c => c.ChannelProgramId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ConductorChannelProgramAgents_ConductorChannelPrograms");
            builder.HasOne(a => a.SamtResourceType).WithMany(b => b.ConductorChannelProgramAgents).HasForeignKey(c => c.ResourceTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ConductorChannelProgramAgents_SAMT_ResourceTypes");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorChannelProgramAgent> builder);
    }

}
// </auto-generated>
