// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorSendHistory
    public partial class ConductorSendHistoryConfiguration : IEntityTypeConfiguration<ConductorSendHistory>
    {
        public void Configure(EntityTypeBuilder<ConductorSendHistory> builder)
        {
            builder.ToTable("ConductorSendHistory", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorSendHistory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ChannelId).HasColumnName(@"ChannelId").HasColumnType("int").IsRequired();
            builder.Property(x => x.BroadcastDate).HasColumnName(@"BroadcastDate").HasColumnType("nchar(10)").IsRequired().IsFixedLength().HasMaxLength(10);
            builder.Property(x => x.ConductorId).HasColumnName(@"ConductorId").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UsedAtDateTime).HasColumnName(@"UsedAtDateTime").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorSendHistory> builder);
    }

}
// </auto-generated>
