// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorTaminGroups
    public partial class ConductorTaminGroupConfiguration : IEntityTypeConfiguration<ConductorTaminGroup>
    {
        public void Configure(EntityTypeBuilder<ConductorTaminGroup> builder)
        {
            builder.ToTable("ConductorTaminGroups", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorTaminGroups").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(150)").IsRequired().HasMaxLength(150);
            builder.Property(x => x.ChannelId).HasColumnName(@"ChannelID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ColorNo).HasColumnName(@"ColorNo").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorTaminGroup> builder);
    }

}
// </auto-generated>
