// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorBox
    public partial class ConductorBoxConfiguration : IEntityTypeConfiguration<ConductorBox>
    {
        public void Configure(EntityTypeBuilder<ConductorBox> builder)
        {
            builder.ToTable("ConductorBox", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorBox").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.BoxNumber).HasColumnName(@"BoxNumber").HasColumnType("int").IsRequired();
            builder.Property(x => x.ChannelId).HasColumnName(@"ChannelID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsSent).HasColumnName(@"IsSent").HasColumnType("bit").IsRequired();
            builder.Property(x => x.SentDate).HasColumnName(@"SentDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.TargetTime).HasColumnName(@"TargetTime").HasColumnType("time").IsRequired(false);
            builder.Property(x => x.TargetTime2).HasColumnName(@"TargetTime2").HasColumnType("time").IsRequired(false);
            builder.Property(x => x.TargetTimeType).HasColumnName(@"TargetTimeType").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorBox> builder);
    }

}
// </auto-generated>
