// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorChannelProgCategory
    public partial class ConductorChannelProgCategoryConfiguration : IEntityTypeConfiguration<ConductorChannelProgCategory>
    {
        public void Configure(EntityTypeBuilder<ConductorChannelProgCategory> builder)
        {
            builder.ToTable("ConductorChannelProgCategory", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorChannelProgCategory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ChannelId).HasColumnName(@"ChannelId").HasColumnType("int").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorChannelProgCategory> builder);
    }

}
// </auto-generated>
