// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorBroadcastLicenses
    public partial class ConductorBroadcastLicensConfiguration : IEntityTypeConfiguration<ConductorBroadcastLicens>
    {
        public void Configure(EntityTypeBuilder<ConductorBroadcastLicens> builder)
        {
            builder.ToTable("ConductorBroadcastLicenses", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorBroadcastLicenses").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.LicenseDate).HasColumnName(@"LicenseDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LicenseNumber).HasColumnName(@"LicenseNumber").HasColumnType("nvarchar(20)").IsRequired(false).HasMaxLength(20);
            builder.Property(x => x.ProgramId).HasColumnName(@"ProgramID").HasColumnType("int").IsRequired();
            builder.Property(x => x.GroupId).HasColumnName(@"GroupID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ClacketNumber).HasColumnName(@"ClacketNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TapeNumber).HasColumnName(@"TapeNumber").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.ProgramSubject).HasColumnName(@"ProgramSubject").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.PartSummary).HasColumnName(@"PartSummary").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ConductorId).HasColumnName(@"ConductorId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasOccasion).HasColumnName(@"HasOccasion").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Occasion).HasColumnName(@"Occasion").HasColumnType("nvarchar(1500)").IsRequired(false).HasMaxLength(1500);
            builder.Property(x => x.ImageSource).HasColumnName(@"ImageSource").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.SoundBandId).HasColumnName(@"SoundBandID").HasColumnType("int").IsRequired();
            builder.Property(x => x.FileFormatId).HasColumnName(@"FileFormatID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ImageRatioId).HasColumnName(@"ImageRatioID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductionYear).HasColumnName(@"ProductionYear").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Presenter).HasColumnName(@"Presenter").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.Guest).HasColumnName(@"Guest").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.Expert).HasColumnName(@"Expert").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.MainActors).HasColumnName(@"MainActors").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.OtherAgents).HasColumnName(@"OtherAgents").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.SmsQuestion).HasColumnName(@"SmsQuestion").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.HasSubtitle).HasColumnName(@"HasSubtitle").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.SubTitle).HasColumnName(@"SubTitle").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ProgramItem1).HasColumnName(@"ProgramItem1").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem2).HasColumnName(@"ProgramItem2").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem3).HasColumnName(@"ProgramItem3").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem4).HasColumnName(@"ProgramItem4").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem5).HasColumnName(@"ProgramItem5").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem6).HasColumnName(@"ProgramItem6").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem7).HasColumnName(@"ProgramItem7").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem8).HasColumnName(@"ProgramItem8").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.ProgramItem9).HasColumnName(@"ProgramItem9").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.LicenseFilePath).HasColumnName(@"LicenseFilePath").HasColumnType("nvarchar(2500)").IsRequired(false).HasMaxLength(2500);
            builder.Property(x => x.SendBy).HasColumnName(@"SendBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LicenseImg).HasColumnName(@"licenseImg").HasColumnType("nvarchar(400)").IsRequired(false).HasMaxLength(400);
            builder.Property(x => x.ProductionType).HasColumnName(@"ProductionType").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorBroadcastLicens> builder);
    }

}
// </auto-generated>
