// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ConductorSubTitles
    public partial class ConductorSubTitleConfiguration : IEntityTypeConfiguration<ConductorSubTitle>
    {
        public void Configure(EntityTypeBuilder<ConductorSubTitle> builder)
        {
            builder.ToTable("ConductorSubTitles", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ConductorSubTitle").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ConductorId).HasColumnName(@"ConductorID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("nvarchar(150)").IsRequired(false).HasMaxLength(150);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("ntext").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreateDatetime).HasColumnName(@"CreateDatetime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.DeletedBy).HasColumnName(@"DeletedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastModificationDatetime).HasColumnName(@"LastModificationDatetime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ItemType).HasColumnName(@"ItemType").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProgramId).HasColumnName(@"ProgramId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ClacketNo).HasColumnName(@"ClacketNo").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ConductorSubTitle> builder);
    }

}
// </auto-generated>
