// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // DispatchTypeValue
    public partial class DispatchTypeValueConfiguration : IEntityTypeConfiguration<DispatchTypeValue>
    {
        public void Configure(EntityTypeBuilder<DispatchTypeValue> builder)
        {
            builder.ToTable("DispatchTypeValue", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_DipatchTypeValue").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.DispatchId).HasColumnName(@"DispatchId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ConductorItemDispatch).WithMany(b => b.DispatchTypeValues).HasForeignKey(c => c.DispatchId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DispatchTypeValue_ConductorItemDispatch");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<DispatchTypeValue> builder);
    }

}
// </auto-generated>
