// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // IdentityResourceProperties
    public partial class IdentityResourcePropertyConfiguration : IEntityTypeConfiguration<IdentityResourceProperty>
    {
        public void Configure(EntityTypeBuilder<IdentityResourceProperty> builder)
        {
            builder.ToTable("IdentityResourceProperties", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_IdentityResourceProperties").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.IdentityResourceId).HasColumnName(@"IdentityResourceId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Key).HasColumnName(@"Key").HasColumnType("nvarchar(250)").IsRequired().HasMaxLength(250);
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar(2000)").IsRequired().HasMaxLength(2000);

            // Foreign keys
            builder.HasOne(a => a.IdentityResource).WithMany(b => b.IdentityResourceProperties).HasForeignKey(c => c.IdentityResourceId).HasConstraintName("FK_IdentityResourceProperties_IdentityResources_IdentityResourceId");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<IdentityResourceProperty> builder);
    }

}
// </auto-generated>
