// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Init_ProgramSubjects
    public partial class InitProgramSubjectConfiguration : IEntityTypeConfiguration<InitProgramSubject>
    {
        public void Configure(EntityTypeBuilder<InitProgramSubject> builder)
        {
            builder.ToTable("Init_ProgramSubjects", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Init_ProgramSubjects").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<InitProgramSubject> builder);
    }

}
// </auto-generated>
