// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // LinkCategories
    public partial class LinkCategoryConfiguration : IEntityTypeConfiguration<LinkCategory>
    {
        public void Configure(EntityTypeBuilder<LinkCategory> builder)
        {
            builder.ToTable("LinkCategories", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_LinkCategory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.ShowTitle).HasColumnName(@"ShowTitle").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ShowInModule).HasColumnName(@"ShowInModule").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<LinkCategory> builder);
    }

}
// </auto-generated>
