// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Menus
    public partial class MenuConfiguration : IEntityTypeConfiguration<Menu>
    {
        public void Configure(EntityTypeBuilder<Menu> builder)
        {
            builder.ToTable("Menus", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ispgMenus").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.MainMenuId).HasColumnName(@"MainMenuID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ParentId).HasColumnName(@"ParentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(255)").IsRequired().HasMaxLength(255);
            builder.Property(x => x.Link).HasColumnName(@"Link").HasColumnType("varchar(400)").IsRequired(false).IsUnicode(false).HasMaxLength(400);
            builder.Property(x => x.MenuImage).HasColumnName(@"MenuImage").HasColumnType("varchar(255)").IsRequired(false).IsUnicode(false).HasMaxLength(255);
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();
            builder.Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.LoadAsModule).HasColumnName(@"LoadAsModule").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ClassName).HasColumnName(@"ClassName").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Menu> builder);
    }

}
// </auto-generated>
