// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // NewsRelated
    public partial class NewsRelatedConfiguration : IEntityTypeConfiguration<NewsRelated>
    {
        public void Configure(EntityTypeBuilder<NewsRelated> builder)
        {
            builder.ToTable("NewsRelated", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_NewsRelated").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.NewsId).HasColumnName(@"NewsID").HasColumnType("int").IsRequired();
            builder.Property(x => x.RelatedNewsId).HasColumnName(@"RelatedNewsID").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.News).WithMany(b => b.NewsRelateds).HasForeignKey(c => c.NewsId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NewsRelated_News");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<NewsRelated> builder);
    }

}
// </auto-generated>
