// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // NewsRating
    public partial class NewsRatingConfiguration : IEntityTypeConfiguration<NewsRating>
    {
        public void Configure(EntityTypeBuilder<NewsRating> builder)
        {
            builder.ToTable("NewsRating", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_NewsRating").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.NewsId).HasColumnName(@"NewsID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Score).HasColumnName(@"score").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.News).WithMany(b => b.NewsRatings).HasForeignKey(c => c.NewsId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NewsRating_News");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<NewsRating> builder);
    }

}
// </auto-generated>
