// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // NewsPriority
    public partial class NewsPriorityConfiguration : IEntityTypeConfiguration<NewsPriority>
    {
        public void Configure(EntityTypeBuilder<NewsPriority> builder)
        {
            builder.ToTable("NewsPriority", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_NewsPriority").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.NewsId).HasColumnName(@"NewsID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();
            builder.Property(x => x.PriorityId).HasColumnName(@"PriorityID").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.News).WithMany(b => b.NewsPriorities).HasForeignKey(c => c.NewsId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_NewsPriority_News");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<NewsPriority> builder);
    }

}
// </auto-generated>
