// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // OauthLogs
    public partial class OauthLogConfiguration : IEntityTypeConfiguration<OauthLog>
    {
        public void Configure(EntityTypeBuilder<OauthLog> builder)
        {
            builder.ToTable("OauthLogs", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_OauthLogs").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Token).HasColumnName(@"Token").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Response).HasColumnName(@"Response").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.DateReg).HasColumnName(@"DateReg").HasColumnType("datetime").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<OauthLog> builder);
    }

}
// </auto-generated>
