// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Pakhsh_TabletShiftLogs
    public partial class PakhshTabletShiftLogConfiguration : IEntityTypeConfiguration<PakhshTabletShiftLog>
    {
        public void Configure(EntityTypeBuilder<PakhshTabletShiftLog> builder)
        {
            builder.ToTable("Pakhsh_TabletShiftLogs", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Pakhsh_TabletShiftLogs").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.TabletShiftId).HasColumnName(@"TabletShiftID").HasColumnType("int").IsRequired();
            builder.Property(x => x.PreAgentId).HasColumnName(@"PreAgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.NextAgentId).HasColumnName(@"NextAgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.NextAgent).WithMany(b => b.PakhshTabletShiftLogs_NextAgentId).HasForeignKey(c => c.NextAgentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons1");
            builder.HasOne(a => a.PakhshTabletShift).WithMany(b => b.PakhshTabletShiftLogs).HasForeignKey(c => c.TabletShiftId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Pakhsh_TabletShiftLogs_Pakhsh_TabletShifts");
            builder.HasOne(a => a.PreAgent).WithMany(b => b.PakhshTabletShiftLogs_PreAgentId).HasForeignKey(c => c.PreAgentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Pakhsh_TabletShiftLogs_Pakhsh_Persons");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<PakhshTabletShiftLog> builder);
    }

}
// </auto-generated>
