// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // PortalAddresses
    public partial class PortalAddressConfiguration : IEntityTypeConfiguration<PortalAddress>
    {
        public void Configure(EntityTypeBuilder<PortalAddress> builder)
        {
            builder.ToTable("PortalAddresses", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_PortalAddresses").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.DomainAddress).HasColumnName(@"DomainAddress").HasColumnType("nvarchar(60)").IsRequired().HasMaxLength(60);
            builder.Property(x => x.Desciption).HasColumnName(@"Desciption").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.PortalAddresses).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PortalAddresses_Portals");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<PortalAddress> builder);
    }

}
// </auto-generated>
