// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ProgramAgeRanges
    public partial class ProgramAgeRanxConfiguration : IEntityTypeConfiguration<ProgramAgeRanx>
    {
        public void Configure(EntityTypeBuilder<ProgramAgeRanx> builder)
        {
            builder.ToTable("ProgramAgeRanges", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ProgramAgeRanges").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();
            builder.Property(x => x.ChannelId).HasColumnName(@"ChannelID").HasColumnType("int").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ProgramAgeRanx> builder);
    }

}
// </auto-generated>
