// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Questions
    public partial class QuestionConfiguration : IEntityTypeConfiguration<Question>
    {
        public void Configure(EntityTypeBuilder<Question> builder)
        {
            builder.ToTable("Questions", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Questions").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.Family).HasColumnName(@"Family").HasColumnType("nvarchar(400)").IsRequired(false).HasMaxLength(400);
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("varchar(200)").IsRequired(false).IsUnicode(false).HasMaxLength(200);
            builder.Property(x => x.Ask).HasColumnName(@"Ask").HasColumnType("nvarchar(4000)").IsRequired().HasMaxLength(4000);
            builder.Property(x => x.Answer).HasColumnName(@"Answer").HasColumnType("ntext").IsRequired(false);
            builder.Property(x => x.Active).HasColumnName(@"Active").HasColumnType("bit").IsRequired();
            builder.Property(x => x.QuestionDate).HasColumnName(@"QuestionDate").HasColumnType("char(10)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.QuestionCode).HasColumnName(@"QuestionCode").HasColumnType("char(9)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(9);
            builder.Property(x => x.Ip).HasColumnName(@"IP").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200);
            builder.Property(x => x.Publishdate).HasColumnName(@"Publishdate").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Question> builder);
    }

}
// </auto-generated>
