// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // RayanModuleHelps
    public partial class RayanModuleHelpConfiguration : IEntityTypeConfiguration<RayanModuleHelp>
    {
        public void Configure(EntityTypeBuilder<RayanModuleHelp> builder)
        {
            builder.ToTable("RayanModuleHelps", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_RayanModuleHelp").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.ModuleKey).HasColumnName(@"ModuleKey").HasColumnType("nvarchar(70)").IsRequired().HasMaxLength(70);
            builder.Property(x => x.HelpContent).HasColumnName(@"HelpContent").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.VideoLink).HasColumnName(@"VideoLink").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<RayanModuleHelp> builder);
    }

}
// </auto-generated>
