// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // RayanCounterOnlineUsers
    public partial class RayanCounterOnlineUserConfiguration : IEntityTypeConfiguration<RayanCounterOnlineUser>
    {
        public void Configure(EntityTypeBuilder<RayanCounterOnlineUser> builder)
        {
            builder.ToTable("RayanCounterOnlineUsers", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_RayanCounterOnlineUsers").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ViewDateTime).HasColumnName(@"ViewDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ViewDate).HasColumnName(@"ViewDate").HasColumnType("nchar(10)").IsRequired().IsFixedLength().HasMaxLength(10);
            builder.Property(x => x.ViewTime).HasColumnName(@"ViewTime").HasColumnType("nchar(5)").IsRequired().IsFixedLength().HasMaxLength(5);
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.UserIp).HasColumnName(@"UserIP").HasColumnType("nvarchar(20)").IsRequired(false).HasMaxLength(20);
            builder.Property(x => x.SessionId).HasColumnName(@"SessionID").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.RayanCounterOnlineUsers).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_RayanCounterOnlineUsers_Portals");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<RayanCounterOnlineUser> builder);
    }

}
// </auto-generated>
