// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // requestBackup2
    public partial class RequestBackup2Configuration : IEntityTypeConfiguration<RequestBackup2>
    {
        public void Configure(EntityTypeBuilder<RequestBackup2> builder)
        {
            builder.ToTable("requestBackup2", "dbo");
            builder.HasKey(x => x.RequestId);

            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.BaseYear).HasColumnName(@"BaseYear").HasColumnType("varchar(5)").IsRequired(false).IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.Program).HasColumnName(@"Program").HasColumnType("nvarchar(250)").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.GroupId).HasColumnName(@"GroupID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LicenseNumber).HasColumnName(@"LicenseNumber").HasColumnType("varchar(17)").IsRequired(false).IsUnicode(false).HasMaxLength(17);
            builder.Property(x => x.ExportationDate).HasColumnName(@"ExportationDate").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.ProgramGradeId).HasColumnName(@"ProgramGradeID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.StructureId).HasColumnName(@"StructureID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LicenseProgramCount).HasColumnName(@"LicenseProgramCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TotalTimeMin).HasColumnName(@"TotalTimeMin").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ApprovedStartDate).HasColumnName(@"ApprovedStartDate").HasColumnType("nchar(10)").IsRequired(false).IsFixedLength().HasMaxLength(10);
            builder.Property(x => x.ApprovedEndDate).HasColumnName(@"ApprovedEndDate").HasColumnType("nchar(10)").IsRequired(false).IsFixedLength().HasMaxLength(10);
            builder.Property(x => x.ApprovedBroadCastDate).HasColumnName(@"ApprovedBroadCastDate").HasColumnType("nchar(10)").IsRequired(false).IsFixedLength().HasMaxLength(10);
            builder.Property(x => x.StructureTypeId).HasColumnName(@"StructureTypeID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ArchivedPercent).HasColumnName(@"ArchivedPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RecordedPercent).HasColumnName(@"RecordedPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LivePercent).HasColumnName(@"LivePercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EstimateDate).HasColumnName(@"EstimateDate").HasColumnType("char(10)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.EstimateNumer).HasColumnName(@"EstimateNumer").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.ProgramNumber).HasColumnName(@"ProgramNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Time).HasColumnName(@"Time").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MinuteRate).HasColumnName(@"MinuteRate").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.DirectPayment).HasColumnName(@"DirectPayment").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.OtherDesc).HasColumnName(@"OtherDesc").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.EvaluationType).HasColumnName(@"EvaluationType").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TheParticipation).HasColumnName(@"TheParticipation").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.NumberParticipation).HasColumnName(@"NumberParticipation").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasRevisoryEstimation).HasColumnName(@"HasRevisoryEstimation").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.CorrectiveDesc).HasColumnName(@"CorrectiveDesc").HasColumnType("nvarchar(510)").IsRequired(false).HasMaxLength(510);
            builder.Property(x => x.EvaluationEstimateDate).HasColumnName(@"EvaluationEstimateDate").HasColumnType("char(10)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.EvaluationProgramNumber).HasColumnName(@"evaluationProgramNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluationTime).HasColumnName(@"EvaluationTime").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluationMinuteRate).HasColumnName(@"EvaluationMinuteRate").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.EvaluationDirectPayment).HasColumnName(@"EvaluationDirectPayment").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.EvaluationDesc).HasColumnName(@"EvaluationDesc").HasColumnType("nvarchar(3000)").IsRequired(false).HasMaxLength(3000);
            builder.Property(x => x.EvaluatedNumberPartnership).HasColumnName(@"EvaluatedNumberPartnership").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluatedThePartnership).HasColumnName(@"EvaluatedThePartnership").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<RequestBackup2> builder);
    }

}
// </auto-generated>
