// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_RequestProductionSubject
    public partial class SamtRequestProductionSubjectConfiguration : IEntityTypeConfiguration<SamtRequestProductionSubject>
    {
        public void Configure(EntityTypeBuilder<SamtRequestProductionSubject> builder)
        {
            builder.ToTable("SAMT_RequestProductionSubject", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_RequestProductionSubject").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProductionAdminReportsId).HasColumnName(@"ProductionAdminReportsID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Parts).HasColumnName(@"Parts").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Time).HasColumnName(@"Time").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProgramType).HasColumnName(@"ProgramType").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsLive).HasColumnName(@"IsLive").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsNew).HasColumnName(@"IsNew").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsDirectEvent).HasColumnName(@"IsDirectEvent").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.FromPlayDate).HasColumnName(@"FromPlayDate").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);
            builder.Property(x => x.FromPlayDateTime).HasColumnName(@"FromPlayDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ToPlayDate).HasColumnName(@"ToPlayDate").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);
            builder.Property(x => x.ToPlayDateTime).HasColumnName(@"ToPlayDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.PlayDate).HasColumnName(@"PlayDate").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);
            builder.Property(x => x.PlayDateTime).HasColumnName(@"PlayDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.PlayTime).HasColumnName(@"PlayTime").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.IsIndicator).HasColumnName(@"IsIndicator").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Summary).HasColumnName(@"Summary").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.SubjectType).HasColumnName(@"SubjectType").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Mojri).HasColumnName(@"Mojri").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Expert).HasColumnName(@"Expert").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Year).HasColumnName(@"Year").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtRequestProductionSubject> builder);
    }

}
// </auto-generated>
