// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_StructureTypes
    public partial class SamtStructureTypeConfiguration : IEntityTypeConfiguration<SamtStructureType>
    {
        public void Configure(EntityTypeBuilder<SamtStructureType> builder)
        {
            builder.ToTable("SAMT_StructureTypes", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatStructureTypes").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtStructureType> builder);
    }

}
// </auto-generated>
