// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ProductionAgentSteps
    public partial class SamtProductionAgentStepConfiguration : IEntityTypeConfiguration<SamtProductionAgentStep>
    {
        public void Configure(EntityTypeBuilder<SamtProductionAgentStep> builder)
        {
            builder.ToTable("SAMT_ProductionAgentSteps", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_RequestExperts").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.LogId).HasColumnName(@"LogID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            builder.Property(x => x.ExpertId).HasColumnName(@"ExpertID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MojriId).HasColumnName(@"MojriID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.GuestPresent).HasColumnName(@"GuestPresent").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.GuestTelephonic).HasColumnName(@"GuestTelephonic").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.Step).HasColumnName(@"Step").HasColumnType("int").IsRequired();
            builder.Property(x => x.ExpertName).HasColumnName(@"ExpertName").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.MojriName).HasColumnName(@"MojriName").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);

            builder.HasIndex(x => x.LogId).HasDatabaseName("NonClusteredIndex-20201207-174713");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProductionAgentStep> builder);
    }

}
// </auto-generated>
