// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_RequestCosts
    public partial class SamtRequestCostConfiguration : IEntityTypeConfiguration<SamtRequestCost>
    {
        public void Configure(EntityTypeBuilder<SamtRequestCost> builder)
        {
            builder.ToTable("SAMT_RequestCosts", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_RequestCosts").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CategoryId).HasColumnName(@"CategoryID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Cost).HasColumnName(@"Cost").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtRequestCost> builder);
    }

}
// </auto-generated>
