// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMTProposalDPT
    public partial class SamtProposalDptConfiguration : IEntityTypeConfiguration<SamtProposalDpt>
    {
        public void Configure(EntityTypeBuilder<SamtProposalDpt> builder)
        {
            builder.ToTable("SAMTProposalDPT", "dbo");
            builder.HasKey(x => new { x.ProposalDptid, x.ProposalId, x.Dptid, x.DptPercent, x.FetchDate });

            builder.Property(x => x.ProposalDptid).HasColumnName(@"ProposalDPTID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProposalId).HasColumnName(@"ProposalID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Dptid).HasColumnName(@"DPTID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DptPercent).HasColumnName(@"DPTPercent").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProposalIdCore).HasColumnName(@"ProposalIDCore").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProductId).HasColumnName(@"ProductID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Uid).HasColumnName(@"UID").HasColumnType("varchar(17)").IsRequired(false).IsUnicode(false).HasMaxLength(17);
            builder.Property(x => x.Uid2).HasColumnName(@"UID2").HasColumnType("varchar(17)").IsRequired(false).IsUnicode(false).HasMaxLength(17);
            builder.Property(x => x.HasCorrection).HasColumnName(@"HasCorrection").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.ProposalTitle).HasColumnName(@"ProposalTitle").HasColumnType("nvarchar(250)").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProductionLevelId).HasColumnName(@"ProductionLevelID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EpisodeCount).HasColumnName(@"EpisodeCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EpisodeTimeMin).HasColumnName(@"EpisodeTimeMin").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EpisodeTimeSec).HasColumnName(@"EpisodeTimeSec").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TotalTimeMin).HasColumnName(@"TotalTimeMin").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TotalTimeSec).HasColumnName(@"TotalTimeSec").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.FormatId).HasColumnName(@"FormatID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LivePercent).HasColumnName(@"LivePercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RecordedPercent).HasColumnName(@"RecordedPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ArchivedPercent).HasColumnName(@"ArchivedPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.GroupId).HasColumnName(@"GroupID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.GroupId2).HasColumnName(@"GroupID2").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AudienceGenderId).HasColumnName(@"AudienceGenderID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EducationId).HasColumnName(@"EducationID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ApproachId).HasColumnName(@"ApproachID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProcessSubjectId).HasColumnName(@"ProcessSubjectID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PresentationTypeId).HasColumnName(@"PresentationTypeID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasEvent).HasColumnName(@"HasEvent").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.HasParticipation).HasColumnName(@"HasParticipation").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.ParticipationPercent).HasColumnName(@"ParticipationPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BroadcastDurationId).HasColumnName(@"BroadcastDurationID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BroadcastOther).HasColumnName(@"BroadcastOther").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.BroadcastTimeMorning).HasColumnName(@"BroadcastTimeMorning").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.BroadcastTimeNoon).HasColumnName(@"BroadcastTimeNoon").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.BroadcastTimeEvening).HasColumnName(@"BroadcastTimeEvening").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.BroadcastTimeNight).HasColumnName(@"BroadcastTimeNight").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.BroadcastTimeMidNight).HasColumnName(@"BroadcastTimeMidNight").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.HasSms).HasColumnName(@"HasSMS").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.SmsNumber).HasColumnName(@"SMSNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasWebSite).HasColumnName(@"HasWebSite").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.DomainTitle1).HasColumnName(@"DomainTitle1").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.DomainTitle2).HasColumnName(@"DomainTitle2").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.HasSocialNetwork).HasColumnName(@"HasSocialNetwork").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.SocialNetworkTitle).HasColumnName(@"SocialNetworkTitle").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.FirstId).HasColumnName(@"FirstID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ParentId).HasColumnName(@"ParentID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreationDate).HasColumnName(@"CreationDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.CreatedById).HasColumnName(@"CreatedByID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.DeleteDate).HasColumnName(@"DeleteDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.DeletedById).HasColumnName(@"DeletedByID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsProducer).HasColumnName(@"IsProducer").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsGroup).HasColumnName(@"IsGroup").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsChannel).HasColumnName(@"IsChannel").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsAdministration).HasColumnName(@"IsAdministration").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsResult).HasColumnName(@"IsResult").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProposalDate).HasColumnName(@"ProposalDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.PersianDate).HasColumnName(@"PersianDate").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.GroupSignature).HasColumnName(@"GroupSignature").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ChannelSignature).HasColumnName(@"ChannelSignature").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.AdministrationSignature).HasColumnName(@"AdministrationSignature").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Attachment).HasColumnName(@"Attachment").HasColumnType("varbinary(max)").IsRequired(false);
            builder.Property(x => x.AttachmentType).HasColumnName(@"AttachmentType").HasColumnType("varchar(200)").IsRequired(false).IsUnicode(false).HasMaxLength(200);
            builder.Property(x => x.AttachmentShora).HasColumnName(@"AttachmentShora").HasColumnType("varbinary(max)").IsRequired(false);
            builder.Property(x => x.AttachmentShoraType).HasColumnName(@"AttachmentShoraType").HasColumnType("varchar(200)").IsRequired(false).IsUnicode(false).HasMaxLength(200);
            builder.Property(x => x.IdeaId).HasColumnName(@"IdeaID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ChannelDate).HasColumnName(@"ChannelDate").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.AnimationGroupId).HasColumnName(@"AnimationGroupId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsIndex).HasColumnName(@"IsIndex").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.FetchDate).HasColumnName(@"FetchDate").HasColumnType("datetime").IsRequired().ValueGeneratedNever();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProposalDpt> builder);
    }

}
// </auto-generated>
