// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ProposalEducation
    public partial class SamtProposalEducationConfiguration : IEntityTypeConfiguration<SamtProposalEducation>
    {
        public void Configure(EntityTypeBuilder<SamtProposalEducation> builder)
        {
            builder.ToTable("SAMT_ProposalEducation", "dbo");
            builder.HasKey(x => x.ProposalEducationId).HasName("PK_SAMT_ProposalEducation").IsClustered();

            builder.Property(x => x.ProposalEducationId).HasColumnName(@"ProposalEducationID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Moghadamati).HasColumnName(@"Moghadamati").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Takmili).HasColumnName(@"Takmili").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Sayer).HasColumnName(@"Sayer").HasColumnType("bit").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProposalEducation> builder);
    }

}
// </auto-generated>
