// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ProductionProgresses
    public partial class SamtProductionProgressConfiguration : IEntityTypeConfiguration<SamtProductionProgress>
    {
        public void Configure(EntityTypeBuilder<SamtProductionProgress> builder)
        {
            builder.ToTable("SAMT_ProductionProgresses", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_ProductionProgresses").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ReportDate).HasColumnName(@"ReportDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.WritingProgress).HasColumnName(@"WritingProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PreProductProgress).HasColumnName(@"PreProductProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProductProgress).HasColumnName(@"ProductProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AfterProductProgress).HasColumnName(@"AfterProductProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.DecisiveProduction).HasColumnName(@"DecisiveProduction").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ResearchProgress).HasColumnName(@"ResearchProgress").HasColumnType("int").IsRequired();
            builder.Property(x => x.ModifyDate).HasColumnName(@"ModifyDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.CreatorId).HasColumnName(@"CreatorId").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProductionProgress> builder);
    }

}
// </auto-generated>
