// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ResourceCategory
    public partial class SamtResourceCategoryConfiguration : IEntityTypeConfiguration<SamtResourceCategory>
    {
        public void Configure(EntityTypeBuilder<SamtResourceCategory> builder)
        {
            builder.ToTable("SAMT_ResourceCategory", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_ResourceCategory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.CreationDateTime).HasColumnName(@"CreationDateTime").HasColumnType("smalldatetime").IsRequired();
            builder.Property(x => x.IsExpired).HasColumnName(@"IsExpired").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ExpireDateTime).HasColumnName(@"ExpireDateTime").HasColumnType("smalldatetime").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtResourceCategory> builder);
    }

}
// </auto-generated>
