// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_HRCooperationType
    public partial class SamtHrCooperationTypeConfiguration : IEntityTypeConfiguration<SamtHrCooperationType>
    {
        public void Configure(EntityTypeBuilder<SamtHrCooperationType> builder)
        {
            builder.ToTable("SAMT_HRCooperationType", "dbo");
            builder.HasKey(x => x.HrCooperationTypeId).HasName("PK_SAMT_HRCooperationType").IsClustered();

            builder.Property(x => x.HrCooperationTypeId).HasColumnName(@"HRCooperationTypeID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.HrCooperationTypeTitle).HasColumnName(@"HRCooperationTypeTitle").HasColumnType("nvarchar(500)").IsRequired().HasMaxLength(500);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtHrCooperationType> builder);
    }

}
// </auto-generated>
