// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_Subjects
    public partial class SamtSubjectConfiguration : IEntityTypeConfiguration<SamtSubject>
    {
        public void Configure(EntityTypeBuilder<SamtSubject> builder)
        {
            builder.ToTable("SAMT_Subjects", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatSubjects_1").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.SubjectLevel).HasColumnName(@"SubjectLevel").HasColumnType("int").IsRequired();
            builder.Property(x => x.SubjectOrder).HasColumnName(@"SubjectOrder").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtSubject> builder);
    }

}
// </auto-generated>
