// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMTV2_PlanYearlyCommitment
    public partial class Samtv2PlanYearlyCommitmentConfiguration : IEntityTypeConfiguration<Samtv2PlanYearlyCommitment>
    {
        public void Configure(EntityTypeBuilder<Samtv2PlanYearlyCommitment> builder)
        {
            builder.ToTable("SAMTV2_PlanYearlyCommitment", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMTV2_PlanYearlyCommitment").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();
            builder.Property(x => x.PlanTopicId).HasColumnName(@"PlanTopic_ID").HasColumnType("int").IsRequired();
            builder.Property(x => x.PlanTopicPercent).HasColumnName(@"PlanTopic_Percent").HasColumnType("int").IsRequired();
            builder.Property(x => x.PlanTopicTime).HasColumnName(@"PlanTopic_Time").HasColumnType("int").IsRequired();
            builder.Property(x => x.Years).HasColumnName(@"Years").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsRequired();
            builder.Property(x => x.ModifyDate).HasColumnName(@"ModifyDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifyBy).HasColumnName(@"ModifyBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.FetchDate).HasColumnName(@"FetchDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Samtv2PlanTopic).WithMany(b => b.Samtv2PlanYearlyCommitment).HasForeignKey(c => c.PlanTopicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV2_PlanYearlyCommitment_SAMTV2_PlanTopics");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Samtv2PlanYearlyCommitment> builder);
    }

}
// </auto-generated>
