// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SamT_Users
    public partial class SamTUserConfiguration : IEntityTypeConfiguration<SamTUser>
    {
        public void Configure(EntityTypeBuilder<SamTUser> builder)
        {
            builder.ToTable("SamT_Users", "dbo");
            builder.HasKey(x => new { x.Id, x.Username, x.FirstName, x.LastName });

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Username).HasColumnName(@"Username").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100).ValueGeneratedNever();
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200).ValueGeneratedNever();
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200).ValueGeneratedNever();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamTUser> builder);
    }

}
// </auto-generated>
