// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMTV3_Monitoring
    public partial class Samtv3MonitoringConfiguration : IEntityTypeConfiguration<Samtv3Monitoring>
    {
        public void Configure(EntityTypeBuilder<Samtv3Monitoring> builder)
        {
            builder.ToTable("SAMTV3_Monitoring", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMTV3_Monitoring").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Part).HasColumnName(@"Part").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.FirstGradeTopicId).HasColumnName(@"FirstGradeTopicId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.SecondGradeTopicId).HasColumnName(@"SecondGradeTopicId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ThirdGradeTopicId).HasColumnName(@"ThirdGradeTopicId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ImportanceId).HasColumnName(@"ImportanceId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BroadcastTypeId).HasColumnName(@"BroadcastTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BroadcastDate).HasColumnName(@"BroadcastDate").HasColumnType("date").IsRequired(false);
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("char(5)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("char(5)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.ReportDescription).HasColumnName(@"ReportDescription").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.ExpertDescription).HasColumnName(@"ExpertDescription").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.KeywordDescription).HasColumnName(@"KeywordDescription").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.FirstGradeTopic).WithMany(b => b.Samtv3Monitoring_FirstGradeTopicId).HasForeignKey(c => c.FirstGradeTopicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMTV3_Topics_1");
            builder.HasOne(a => a.SamtRequest).WithMany(b => b.Samtv3Monitoring).HasForeignKey(c => c.RequestId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMT_Requests");
            builder.HasOne(a => a.Samtv3BroadcastType).WithMany(b => b.Samtv3Monitoring).HasForeignKey(c => c.BroadcastTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMTV3_BroadcastTypes");
            builder.HasOne(a => a.Samtv3ImportanceDegree).WithMany(b => b.Samtv3Monitoring).HasForeignKey(c => c.ImportanceId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMTV3_ImportanceDegrees");
            builder.HasOne(a => a.SecondGradeTopic).WithMany(b => b.Samtv3Monitoring_SecondGradeTopicId).HasForeignKey(c => c.SecondGradeTopicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMTV3_Topics_2");
            builder.HasOne(a => a.ThirdGradeTopic).WithMany(b => b.Samtv3Monitoring_ThirdGradeTopicId).HasForeignKey(c => c.ThirdGradeTopicId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMTV3_Monitoring_SAMTV3_Topics_3");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Samtv3Monitoring> builder);
    }

}
// </auto-generated>
