// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ProposalHistory
    public partial class SamtProposalHistoryConfiguration : IEntityTypeConfiguration<SamtProposalHistory>
    {
        public void Configure(EntityTypeBuilder<SamtProposalHistory> builder)
        {
            builder.ToTable("SAMT_ProposalHistory", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_ProposalHistory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired();
            builder.Property(x => x.StatusId).HasColumnName(@"StatusID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreationDateTime).HasColumnName(@"CreationDateTime").HasColumnType("datetime").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProposalHistory> builder);
    }

}
// </auto-generated>
