// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ProposalGender
    public partial class SamtProposalGenderConfiguration : IEntityTypeConfiguration<SamtProposalGender>
    {
        public void Configure(EntityTypeBuilder<SamtProposalGender> builder)
        {
            builder.ToTable("SAMT_ProposalGender", "dbo");
            builder.HasKey(x => x.ProposalGenderId).HasName("PK_SAMT_ProposalGender").IsClustered();

            builder.Property(x => x.ProposalGenderId).HasColumnName(@"ProposalGenderID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Male).HasColumnName(@"male").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Female).HasColumnName(@"Female").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Sayer).HasColumnName(@"Sayer").HasColumnType("bit").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtProposalGender> builder);
    }

}
// </auto-generated>
