// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_RequestLogPlans
    public partial class SamtRequestLogPlanConfiguration : IEntityTypeConfiguration<SamtRequestLogPlan>
    {
        public void Configure(EntityTypeBuilder<SamtRequestLogPlan> builder)
        {
            builder.ToTable("SAMT_RequestLogPlans", "dbo");
            builder.HasKey(x => new { x.Id, x.LogId, x.PlanId });

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.LogId).HasColumnName(@"LogID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PlanId).HasColumnName(@"PlanID").HasColumnType("int").IsRequired().ValueGeneratedNever();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtRequestLogPlan> builder);
    }

}
// </auto-generated>
