// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_BeforeProductions
    public partial class SamtBeforeProductionConfiguration : IEntityTypeConfiguration<SamtBeforeProduction>
    {
        public void Configure(EntityTypeBuilder<SamtBeforeProduction> builder)
        {
            builder.ToTable("SAMT_BeforeProductions", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_BeforeProductions").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ResearchProgress).HasColumnName(@"ResearchProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ResearchDescription).HasColumnName(@"ResearchDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.WritingProgress).HasColumnName(@"WritingProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.WritingPart).HasColumnName(@"WritingPart").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.WritingDescription).HasColumnName(@"WritingDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.LocationProgress).HasColumnName(@"LocationProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LocationDescription).HasColumnName(@"LocationDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.AccessoryProgress).HasColumnName(@"AccessoryProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AccessoryDescription).HasColumnName(@"AccessoryDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.DecorProgress).HasColumnName(@"DecorProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.DecorDescription).HasColumnName(@"DecorDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.MakeupProgress).HasColumnName(@"MakeupProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MakeupDescription).HasColumnName(@"MakeupDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.ClothDesignProgress).HasColumnName(@"ClothDesignProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ClothDesignDescription).HasColumnName(@"ClothDesignDescription").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000);
            builder.Property(x => x.TechnicalFactorsProgress).HasColumnName(@"TechnicalFactorsProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ActorProgress).HasColumnName(@"ActorProgress").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifyDate).HasColumnName(@"ModifyDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.CreatorId).HasColumnName(@"CreatorId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.SamtRequest).WithMany(b => b.SamtBeforeProductions).HasForeignKey(c => c.RequestId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SAMT_BeforeProductions_SAMT_Requests");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtBeforeProduction> builder);
    }

}
// </auto-generated>
