// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMT_ResourceCategoryType
    public partial class SamtResourceCategoryTypeConfiguration : IEntityTypeConfiguration<SamtResourceCategoryType>
    {
        public void Configure(EntityTypeBuilder<SamtResourceCategoryType> builder)
        {
            builder.ToTable("SAMT_ResourceCategoryType", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMT_ResourceCategoryType").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ResourceCategoryId).HasColumnName(@"ResourceCategoryID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ResourceTypeId).HasColumnName(@"ResourceTypeID").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsExpire).HasColumnName(@"IsExpire").HasColumnType("bit").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SamtResourceCategoryType> builder);
    }

}
// </auto-generated>
