// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SAMTV3_StrengthsWeaknesses
    public partial class Samtv3StrengthsWeaknessConfiguration : IEntityTypeConfiguration<Samtv3StrengthsWeakness>
    {
        public void Configure(EntityTypeBuilder<Samtv3StrengthsWeakness> builder)
        {
            builder.ToTable("SAMTV3_StrengthsWeaknesses", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SAMTV3_strengthsWeaknesses").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsWeakness).HasColumnName(@"IsWeakness").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ContentVariable).HasColumnName(@"ContentVariable").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Samtv3StrengthsWeakness> builder);
    }

}
// </auto-generated>
