// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // ShiftTabletConductor
    public partial class ShiftTabletConductorConfiguration : IEntityTypeConfiguration<ShiftTabletConductor>
    {
        public void Configure(EntityTypeBuilder<ShiftTabletConductor> builder)
        {
            builder.ToTable("ShiftTabletConductor", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ShiftTabletConductor").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ShiftTabletId).HasColumnName(@"ShiftTabletId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ConductorDate).HasColumnName(@"ConductorDate").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ShiftTabletConductor> builder);
    }

}
// </auto-generated>
