// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Shift_EmploymentDetail
    public partial class ShiftEmploymentDetailConfiguration : IEntityTypeConfiguration<ShiftEmploymentDetail>
    {
        public void Configure(EntityTypeBuilder<ShiftEmploymentDetail> builder)
        {
            builder.ToTable("Shift_EmploymentDetail", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Shift_EmploymentDetail").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequiredShift).HasColumnName(@"RequiredShift").HasColumnType("int").IsRequired();
            builder.Property(x => x.PerformancePaymentMultiplicationPercent).HasColumnName(@"PerformancePaymentMultiplicationPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PerformancePaymentAmount).HasColumnName(@"performancePaymentAmount").HasColumnType("int").IsRequired();
            builder.Property(x => x.LivePaymenetPercent).HasColumnName(@"LivePaymenetPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LivePaymenetAmount).HasColumnName(@"LivePaymenetAmount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.SpecialDayPaymentAmount).HasColumnName(@"SpecialDayPaymentAmount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.SpecialDayPaymetMultiplicationPercent).HasColumnName(@"SpecialDayPaymetMultiplicationPercent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PortalId).HasColumnName(@"portalID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.UnrequiredShiftPayment).HasColumnName(@"UnrequiredShiftPayment").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CooperationTypeId).HasColumnName(@"CooperationTypeID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.ShiftEmploymentDetails).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Shift_EmploymentDetail_Portals");
            builder.HasOne(a => a.SamtHrCooperationType).WithMany(b => b.ShiftEmploymentDetails).HasForeignKey(c => c.CooperationTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Shift_EmploymentDetail_SAMT_HRCooperationType");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ShiftEmploymentDetail> builder);
    }

}
// </auto-generated>
