// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Shift_ShiftTablet
    public partial class ShiftShiftTabletConfiguration : IEntityTypeConfiguration<ShiftShiftTablet>
    {
        public void Configure(EntityTypeBuilder<ShiftShiftTablet> builder)
        {
            builder.ToTable("Shift_ShiftTablet", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ShiftExecution").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ShiftId).HasColumnName(@"ShiftID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ShiftDate).HasColumnName(@"ShiftDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ShiftWorthPercent).HasColumnName(@"ShiftWorthPercent").HasColumnType("int").IsRequired();
            builder.Property(x => x.ShiftDuration).HasColumnName(@"ShiftDuration").HasColumnType("time").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.HasLivePrograms).HasColumnName(@"HasLivePrograms").HasColumnType("bit").IsRequired();
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.ShiftShiftTablets).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Shift_ShiftTablet_Portals");
            builder.HasOne(a => a.ShiftShift).WithMany(b => b.ShiftShiftTablets).HasForeignKey(c => c.ShiftId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ShiftExecution_PortalShift");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<ShiftShiftTablet> builder);
    }

}
// </auto-generated>
