// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // SimaDataLogs
    public partial class SimaDataLogConfiguration : IEntityTypeConfiguration<SimaDataLog>
    {
        public void Configure(EntityTypeBuilder<SimaDataLog> builder)
        {
            builder.ToTable("SimaDataLogs", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SimaDataLogs").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.RecordCount).HasColumnName(@"RecordCount").HasColumnType("int").IsRequired();
            builder.Property(x => x.TableName).HasColumnName(@"TableName").HasColumnType("nvarchar(150)").IsRequired().HasMaxLength(150);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SimaDataLog> builder);
    }

}
// </auto-generated>
