// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // step5_removed
    public partial class Step5RemovedConfiguration : IEntityTypeConfiguration<Step5Removed>
    {
        public void Configure(EntityTypeBuilder<Step5Removed> builder)
        {
            builder.ToTable("step5_removed", "dbo");
            builder.HasKey(x => new { x.Id, x.LogId, x.Status });

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.LogId).HasColumnName(@"LogID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired().ValueGeneratedNever();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Step5Removed> builder);
    }

}
// </auto-generated>
