// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatEquipmentCategories
    public partial class TelavatEquipmentCategoryConfiguration : IEntityTypeConfiguration<TelavatEquipmentCategory>
    {
        public void Configure(EntityTypeBuilder<TelavatEquipmentCategory> builder)
        {
            builder.ToTable("TelavatEquipmentCategories", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatEquipmentCategories").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Ordering).HasColumnName(@"Ordering").HasColumnType("int").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatEquipmentCategory> builder);
    }

}
// </auto-generated>
