// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatSmsLogs
    public partial class TelavatSmsLogConfiguration : IEntityTypeConfiguration<TelavatSmsLog>
    {
        public void Configure(EntityTypeBuilder<TelavatSmsLog> builder)
        {
            builder.ToTable("TelavatSmsLogs", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatSmsLogs").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            builder.Property(x => x.ItemId).HasColumnName(@"ItemID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Mobile).HasColumnName(@"Mobile").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20);
            builder.Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatSmsLog> builder);
    }

}
// </auto-generated>
