// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatProgramExperts
    public partial class TelavatProgramExpertConfiguration : IEntityTypeConfiguration<TelavatProgramExpert>
    {
        public void Configure(EntityTypeBuilder<TelavatProgramExpert> builder)
        {
            builder.ToTable("TelavatProgramExperts", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatProgramExperts").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar(1000)").IsRequired().HasMaxLength(1000);
            builder.Property(x => x.PortalId).HasColumnName(@"PortalID").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Portal).WithMany(b => b.TelavatProgramExperts).HasForeignKey(c => c.PortalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatProgramExperts_Portals");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatProgramExpert> builder);
    }

}
// </auto-generated>
