// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatProductionAgents
    public partial class TelavatProductionAgentConfiguration : IEntityTypeConfiguration<TelavatProductionAgent>
    {
        public void Configure(EntityTypeBuilder<TelavatProductionAgent> builder)
        {
            builder.ToTable("TelavatProductionAgents", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatProductionAgents").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ProductionReportId).HasColumnName(@"ProductionReportID").HasColumnType("int").IsRequired();
            builder.Property(x => x.AgentId).HasColumnName(@"AgentID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AgentPostId).HasColumnName(@"AgentPostID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            builder.Property(x => x.Date).HasColumnName(@"Date").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);
            builder.Property(x => x.Date2).HasColumnName(@"Date2").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.StartTime2).HasColumnName(@"StartTime2").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.EndTime2).HasColumnName(@"EndTime2").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.ReplaceAgentId).HasColumnName(@"ReplaceAgentID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AgentName).HasColumnName(@"AgentName").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.ReplaceAgentName).HasColumnName(@"ReplaceAgentName").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.PaymentLogDetailId).HasColumnName(@"PaymentLogDetailID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.FinancialNo).HasColumnName(@"FinancialNO").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            builder.Property(x => x.Time2).HasColumnName(@"Time2").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsSet).HasColumnName(@"IsSet").HasColumnType("bit").IsRequired();
            builder.Property(x => x.HasDelay).HasColumnName(@"HasDelay").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.TelavatPaymentLogDetail).WithMany(b => b.TelavatProductionAgents).HasForeignKey(c => c.PaymentLogDetailId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatProductionAgents_TelavatPaymentLogDetails");
            builder.HasOne(a => a.TelavatProductionReport).WithMany(b => b.TelavatProductionAgents).HasForeignKey(c => c.ProductionReportId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatProductionAgents_TelavatProductionReports");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatProductionAgent> builder);
    }

}
// </auto-generated>
