// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TelavatPaymentLogDetails
    public partial class TelavatPaymentLogDetailConfiguration : IEntityTypeConfiguration<TelavatPaymentLogDetail>
    {
        public void Configure(EntityTypeBuilder<TelavatPaymentLogDetail> builder)
        {
            builder.ToTable("TelavatPaymentLogDetails", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_TelavatPaymentLogDetails").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PaymentLogId).HasColumnName(@"PaymentLogID").HasColumnType("int").IsRequired();
            builder.Property(x => x.AmountWageBase).HasColumnName(@"AmountWageBase").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.AmountWageTotal).HasColumnName(@"AmountWageTotal").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.AgentId).HasColumnName(@"AgentID").HasColumnType("int").IsRequired();
            builder.Property(x => x.AgentPostId).HasColumnName(@"AgentPostID").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.SamtResourceType).WithMany(b => b.TelavatPaymentLogDetails).HasForeignKey(c => c.AgentPostId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatPaymentLogDetails_TelavatResourceTypes");
            builder.HasOne(a => a.TelavatPaymentLog).WithMany(b => b.TelavatPaymentLogDetails).HasForeignKey(c => c.PaymentLogId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TelavatPaymentLogDetails_TelavatPaymentLogs");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TelavatPaymentLogDetail> builder);
    }

}
// </auto-generated>
