// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // TEMP_vwBaravordSamt
    public partial class TempVwBaravordSamtConfiguration : IEntityTypeConfiguration<TempVwBaravordSamt>
    {
        public void Configure(EntityTypeBuilder<TempVwBaravordSamt> builder)
        {
            builder.ToTable("TEMP_vwBaravordSamt", "dbo");
            builder.HasKey(x => new { x.EstimateDate, x.ProgramNumber, x.Time, x.EvaluationType });

            builder.Property(x => x.RequestId).HasColumnName(@"RequestID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EstimateDate).HasColumnName(@"EstimateDate").HasColumnType("char(10)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(10).ValueGeneratedNever();
            builder.Property(x => x.EstimateNumer).HasColumnName(@"EstimateNumer").HasColumnType("varchar(20)").IsRequired(false).IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.ProgramNumber).HasColumnName(@"ProgramNumber").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Time).HasColumnName(@"Time").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.MinuteRate).HasColumnName(@"MinuteRate").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.DirectPayment).HasColumnName(@"DirectPayment").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.OtherDesc).HasColumnName(@"OtherDesc").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.EvaluationType).HasColumnName(@"EvaluationType").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TheParticipation).HasColumnName(@"TheParticipation").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.NumberParticipation).HasColumnName(@"NumberParticipation").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.HasRevisoryEstimation).HasColumnName(@"HasRevisoryEstimation").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.CorrectiveDesc).HasColumnName(@"CorrectiveDesc").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.EvaluationEstimateDate).HasColumnName(@"EvaluationEstimateDate").HasColumnType("char(10)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.EvaluationProgramNumber).HasColumnName(@"evaluationProgramNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluationTime).HasColumnName(@"EvaluationTime").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluationMinuteRate).HasColumnName(@"EvaluationMinuteRate").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.EvaluationDirectPayment).HasColumnName(@"EvaluationDirectPayment").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.EvaluationDesc).HasColumnName(@"EvaluationDesc").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.EvaluatedNumberPartnership).HasColumnName(@"EvaluatedNumberPartnership").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EvaluatedThePartnership).HasColumnName(@"EvaluatedThePartnership").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000);
            builder.Property(x => x.LastEstimateDate).HasColumnName(@"LastEstimateDate").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<TempVwBaravordSamt> builder);
    }

}
// </auto-generated>
