// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // VW_SAMTV2_ProgramTopics
    public partial class VwSamtv2ProgramTopicConfiguration : IEntityTypeConfiguration<VwSamtv2ProgramTopic>
    {
        public void Configure(EntityTypeBuilder<VwSamtv2ProgramTopic> builder)
        {
            builder.ToView("VW_SAMTV2_ProgramTopics", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductId).HasColumnName(@"productID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PlanTopicId).HasColumnName(@"PlanTopicID").HasColumnType("int").IsRequired();
            builder.Property(x => x.RootPlanTopicId).HasColumnName(@"RootPlanTopicID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PercentUsed).HasColumnName(@"PercentUsed").HasColumnType("int").IsRequired();
            builder.Property(x => x.FetchDate).HasColumnName(@"FetchDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.RootPlanTopicIdLevel2).HasColumnName(@"RootPlanTopicID_LEVEL2").HasColumnType("int").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<VwSamtv2ProgramTopic> builder);
    }

}
// </auto-generated>
