// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Leopard.Repository
{
    // Widgets
    public partial class WidgetConfiguration : IEntityTypeConfiguration<Widget>
    {
        public void Configure(EntityTypeBuilder<Widget> builder)
        {
            builder.ToTable("Widgets", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Widgets").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PageTemplateId).HasColumnName(@"PageTemplateID").HasColumnType("int").IsRequired();
            builder.Property(x => x.WidgetDefinitionId).HasColumnName(@"WidgetDefinitionID").HasColumnType("int").IsRequired();
            builder.Property(x => x.WidgetSkinPath).HasColumnName(@"WidgetSkinPath").HasColumnType("nvarchar(4000)").IsRequired().HasMaxLength(4000);
            builder.Property(x => x.PanelNo).HasColumnName(@"PanelNo").HasColumnType("int").IsRequired();
            builder.Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType("int").IsRequired();
            builder.Property(x => x.Expanded).HasColumnName(@"Expanded").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);
            builder.Property(x => x.TitleLink).HasColumnName(@"TitleLink").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.State).HasColumnName(@"State").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ShowTitle).HasColumnName(@"ShowTitle").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastModifiedDateTime).HasColumnName(@"LastModifiedDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Published).HasColumnName(@"Published").HasColumnType("bit").IsRequired();
            builder.Property(x => x.NewUrl).HasColumnName(@"NewUrl").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);

            // Foreign keys
            builder.HasOne(a => a.PageTemplate).WithMany(b => b.Widgets).HasForeignKey(c => c.PageTemplateId).HasConstraintName("FK_dbo.Widgets_dbo.PageTemplates_PageTemplateID");
            builder.HasOne(a => a.WidgetDefinition).WithMany(b => b.Widgets).HasForeignKey(c => c.WidgetDefinitionId).HasConstraintName("FK_dbo.Widgets_dbo.WidgetDefinitions_WidgetDefinitionID");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Widget> builder);
    }

}
// </auto-generated>
