// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Leopard.Repository
{
    public partial interface IAdvertisStore : IStoreBase<Advertis>
    {
    }
}
// </auto-generated>
